/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/modelos/MatrixIntercambiador.gltf --transform -j 
Files: public/modelos/MatrixIntercambiador.gltf [24.7MB] > MatrixIntercambiador-transformed.glb [4.54MB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MatrixIntercambiador-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={25.361} position={[-0.368, 0.438, 3.611]} rotation={[0.843, 0.365, -0.149]} />
      <mesh geometry={nodes.Rectangle022.geometry} material={materials.PaletteMaterial001} position={[-1.069, 6.399, -6.607]} scale={-0.01} />
      <mesh geometry={nodes.Rectangle021.geometry} material={materials.PaletteMaterial001} position={[-1.702, 5.846, -4.659]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01} />
      <mesh geometry={nodes.Rectangle014.geometry} material={materials.PaletteMaterial002} position={[-3.239, 6.038, -1.517]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01} />
      <mesh geometry={nodes.Rectangle015.geometry} material={materials.PaletteMaterial001} position={[0.764, 4.2, -3.032]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01} />
      <group position={[2.413, -0.018, 1.86]} rotation={[Math.PI, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh004_3.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh004_4.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh004_5.geometry} material={materials.PaletteMaterial004} />
      </group>
      <group position={[-6.857, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh112.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh112_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-6.707, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh111.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh111_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-6.54, 6.027, -1.408]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh110.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh110_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-6.407, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh109.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh109_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-6.258, 6.538, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh108.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh108_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-6.107, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh107.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh107_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.958, 6.538, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh106.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh106_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.809, 6.322, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh105.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh105_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.654, 5.58, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh104.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh104_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.507, 5.581, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh103.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh103_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.359, 5.575, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh102.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh102_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.207, 5.581, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh101.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh101_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-5.059, 5.575, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh100.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh100_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.907, 5.581, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh099.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh099_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.759, 5.575, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh098.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh098_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.613, 5.586, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh097.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh097_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.466, 5.635, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh096.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh096_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.308, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh095.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh095_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.158, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh094.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh094_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.008, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh093.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh093_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.849, 6.44, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh092.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh092_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.708, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh091.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh091_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.56, 6.555, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh090.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh090_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.411, 6.46, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh089.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh089_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.275, 6.023, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh088.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh088_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-3.108, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh087.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh087_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.958, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh086.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh086_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.808, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh085.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh085_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.649, 5.31, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh084.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh084_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.508, 5.277, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh083.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh083_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.36, 5.257, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh082.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh082_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.209, 5.277, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh081.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh081_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-2.06, 6.224, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh080.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh080_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.909, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh079.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh079_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.76, 6.549, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh078.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh078_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.609, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh077.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh077_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.46, 6.549, -1.406]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh076.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh076_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.309, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh075.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh075_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.16, 6.525, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh074.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh074_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.009, 6.491, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh073.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh073_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.876, 6.008, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh072.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh072_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.709, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh071.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh071_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.559, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh070.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh070_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.409, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh069.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh069_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.26, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh068.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh068_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-0.11, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh067.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh067_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[0.04, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh066.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh066_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[0.19, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh011.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh011_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[0.34, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh007.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[0.49, 5.649, -1.407]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials.Base1} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-1.373, 7.331, -1.594]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.009, 0.009, 0.009]}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials.PaletteMaterial005} />
      </group>
      <mesh geometry={nodes.Object005.geometry} material={materials.PaletteMaterial002} position={[-1.514, 7.333, -1.484]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object006.geometry} material={materials.PaletteMaterial002} position={[-2.409, 4.905, -1.484]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object007.geometry} material={materials.PaletteMaterial002} position={[-3.624, 7.333, -1.484]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <group position={[-3.624, 7.222, -1.594]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.PaletteMaterial005} />
      </group>
      <group position={[-2.409, 4.793, -1.594]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]}>
        <mesh geometry={nodes.Mesh012.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials.PaletteMaterial005} />
      </group>
      <mesh geometry={nodes.Rectangle019.geometry} material={materials.PaletteMaterial002} position={[-6.137, 7.333, -1.503]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Rectangle020.geometry} material={materials.PaletteMaterial002} position={[-5.135, 5.512, -1.503]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
    </group>
  )
}

useGLTF.preload('/MatrixIntercambiador-transformed.glb')
