/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/modelos/MatrixIntercambiador.gltf -k --transform 
Files: public/modelos/MatrixIntercambiador.gltf [26.79MB] > MatrixIntercambiador-transformed.glb [2.67MB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MatrixIntercambiador-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={25.361} position={[-0.368, 0.438, 3.611]} rotation={[0.843, 0.365, -0.149]} />
      <directionalLight name="Sun" intensity={1366} decay={2} position={[0, 4.205, 9.22]} rotation={[-0.081, -0.376, 0.4]} />
      <mesh name="matriz3_k_v_2" geometry={nodes.matriz3_k_v_2.geometry} material={materials.Base1} />
      <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.PaletteMaterial003} />
      <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.PaletteMaterial004} />
      <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.PaletteMaterial001} />
      <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/MatrixIntercambiador-transformed.glb')
