import Perfil1 from "../../../assets/images/DolckertTline/Diseno/Formato/MINIATURAS/PERFIL1.jpg";
export const Mallas = {
  1: {
    matrices: [
      {
        geometries: ["matriz1_a_1", "matriz1_a_2"],
        name: "matriz1_a",
        image: "",
      },
      {
        geometries: ["matriz1_b_1", "matriz1_b_2"],
        name: "matriz1_b",
        image: "",
      },
      {
        geometries: ["matriz1_c_1", "matriz1_c_2"],
        name: "matriz1_c",
        image: "",
      },
    ],
    image: Perfil1,
  },
  2: {
    matrices: [
      {
        geometries: ["matriz2_a_1", "matriz2_a_2"],
        name: "matriz2_a",
        image: "",
      },
      {
        geometries: ["matriz2_b_1", "matriz2_b_2"],
        name: "matriz2_b",
        image: "",
      },
      {
        geometries: ["matriz2_c_1", "matriz2_c_2"],
        name: "matriz2_c",
        image: "",
      },
      {
        geometries: ["matriz2_d_1", "matriz2_d_2"],
        name: "matriz2_d",
        image: "",
      },
      {
        geometries: ["matriz2_e_1", "matriz2_e_2"],
        name: "matriz2_e",
        image: "",
      },
      {
        geometries: ["matriz2_f_1", "matriz2_f_2"],
        name: "matriz2_f",
        image: "",
      },
      {
        geometries: ["matriz2_g_1", "matriz2_g_2"],
        name: "matriz2_g",
        image: "",
      },
      {
        geometries: ["matriz2_h_1", "matriz2_h_2"],
        name: "matriz2_h",
        image: "",
      },
      {
        geometries: ["matriz2_i_1", "matriz2_i_2"],
        name: "matriz2_i",
        image: "",
      },
      {
        geometries: ["matriz2_j_1", "matriz2_j_2"],
        name: "matriz2_j",
        image: "",
      },
      {
        geometries: ["matriz2_k_1", "matriz2_k_2"],
        name: "matriz2_k",
        image: "",
      },
      {
        geometries: ["matriz2_l_1", "matriz2_l_2"],
        name: "matriz2_l",
        image: "",
      },
      {
        geometries: ["matriz2_m_1", "matriz2_m_2"],
        name: "matriz2_m",
        image: "",
      },
      {
        geometries: ["matriz2_n_1", "matriz2_n_2"],
        name: "matriz2_n",
        image: "",
      },
    ],
    image: Perfil1,
  },
  3: {
    matrices: [
      {
        geometries: ["matriz3_a_1", "matriz3_a_2"],
        name: "matriz3_a",
        image: "",
      },
      {
        geometries: ["matriz3_b_1", "matriz3_b_2"],
        name: "matriz3_b",
        image: "",
      },
      {
        geometries: ["matriz3_c_1", "matriz3_c_2"],
        name: "matriz3_c",
        image: "",
      },
      {
        geometries: ["matriz3_d_1", "matriz3_d_2"],
        name: "matriz3_d",
        image: "",
      },
      {
        geometries: ["matriz3_e_1", "matriz3_e_2"],
        name: "matriz3_e",
        image: "",
      },
      {
        geometries: ["matriz3_f_1", "matriz3_f_2"],
        name: "matriz3_f",
        image: "",
      },
      {
        geometries: ["matriz3_g_1", "matriz3_g_2"],
        name: "matriz3_g",
        image: "",
      },
      {
        geometries: ["matriz3_h_1", "matriz3_h_2"],
        name: "matriz3_h",
        image: "",
      },
      {
        geometries: ["matriz3_i_1", "matriz3_i_2"],
        name: "matriz3_i",
        image: "",
      },
      {
        geometries: ["matriz3_j_1", "matriz3_j_2"],
        name: "matriz3_j",
        image: "",
      },
      {
        geometries: ["matriz3_k_1", "matriz3_k_2"],
        name: "matriz3_k",
        image: "",
      },
      {
        geometries: ["matriz3_l_1", "matriz3_l_2"],
        name: "matriz3_l",
        image: "",
      },
      {
        geometries: ["matriz3_m_1", "matriz3_m_2"],
        name: "matriz3_m",
        image: "",
      },
      {
        geometries: ["matriz3_n_1", "matriz3_n_2"],
        name: "matriz3_n",
        image: "",
      },
      {
        geometries: ["matriz3_o_1", "matriz3_o_2"],
        name: "matriz3_o",
        image: "",
      },
      {
        geometries: ["matriz3_p_1", "matriz3_p_2"],
        name: "matriz3_p",
        image: "",
      },
      {
        geometries: ["matriz3_q_1", "matriz3_q_2"],
        name: "matriz3_q",
        image: "",
      },
      {
        geometries: ["matriz3_r_1", "matriz3_r_2"],
        name: "matriz3_r",
        image: "",
      },
      {
        geometries: ["matriz3_s_1", "matriz3_s_2"],
        name: "matriz3_s",
        image: "",
      },
      {
        geometries: ["matriz3_t_1", "matriz3_t_2"],
        name: "matriz3_t",
        image: "",
      },
    ],
    image: Perfil1,
  },
  4: {
    matrices: [
      {
        geometries: ["matriz4_a_1", "matriz4_a_2"],
        name: "matriz4_a",
        image: "",
      },
      {
        geometries: ["matriz4_b_1", "matriz4_b_2"],
        name: "matriz4_b",
        image: "",
      },
    ],
    image: "",
  },
  5: {
    matrices: [
      {
        geometries: ["matriz5_a_1", "matriz5_a_2"],
        name: "matriz5_a",
        image: "",
      },
      {
        geometries: ["matriz5_b_1", "matriz5_b_2"],
        name: "matriz5_b",
        image: "",
      },
      {
        geometries: ["matriz5_c_1", "matriz5_c_2"],
        name: "matriz5_c",
        image: "",
      },
      {
        geometries: ["matriz5_d_1", "matriz5_d_2"],
        name: "matriz5_d",
        image: "",
      },
      {
        geometries: ["matriz5_e_1", "matriz5_e_2"],
        name: "matriz5_e",
        image: "",
      },
      {
        geometries: ["matriz5_f_1", "matriz5_f_2"],
        name: "matriz5_f",
        image: "",
      },
      {
        geometries: ["matriz5_g_1", "matriz5_g_2"],
        name: "matriz5_g",
        image: "",
      },
      {
        geometries: ["matriz5_h_1", "matriz5_h_2"],
        name: "matriz5_h",
        image: "",
      },
      {
        geometries: ["matriz5_i_1", "matriz5_i_2"],
        name: "matriz5_i",
        image: "",
      },
      {
        geometries: ["matriz5_j_1", "matriz5_j_2"],
        name: "matriz5_j",
        image: "",
      },
      {
        geometries: ["matriz5_k_1", "matriz5_k_2"],
        name: "matriz5_k",
        image: "",
      },
      {
        geometries: ["matriz5_l_1", "matriz5_l_2"],
        name: "matriz5_l",
        image: "",
      },
      {
        geometries: ["matriz5_m_1", "matriz5_m_2"],
        name: "matriz5_m",
        image: "",
      },
      {
        geometries: ["matriz5_n_1", "matriz5_n_2"],
        name: "matriz5_n",
        image: "",
      },
      {
        geometries: ["matriz5_o_1", "matriz5_o_2"],
        name: "matriz5_o",
        image: "",
      },
      {
        geometries: ["matriz5_p_1", "matriz5_p_2"],
        name: "matriz5_p",
        image: "",
      },
      {
        geometries: ["matriz5_q_1", "matriz5_q_2"],
        name: "matriz5_q",
        image: "",
      },
      {
        geometries: ["matriz5_r_1", "matriz5_r_2"],
        name: "matriz5_r",
        image: "",
      },
      {
        geometries: ["matriz5_s_1", "matriz5_s_2"],
        name: "matriz5_s",
        image: "",
      },
      {
        geometries: ["matriz5_t_1", "matriz5_t_2"],
        name: "matriz5_t",
        image: "",
      },
    ],
    image: "",
  },
  6: {
    matrices: [
      {
        geometries: ["matriz6_a_1", "matriz6_a_2"],
        name: "matriz6_a",
        image: "",
      },
      {
        geometries: ["matriz6_b_1", "matriz6_b_2"],
        name: "matriz6_b",
        image: "",
      },
    ],
    image: "",
  },
  7: {
    matrices: [
      {
        geometries: ["matriz7_a_1", "matriz7_a_2"],
        name: "matriz7_a",
        image: "",
      },
      {
        geometries: ["matriz7_b_1", "matriz7_b_2"],
        name: "matriz7_b",
        image: "",
      },
      {
        geometries: ["matriz7_c_1", "matriz7_c_2"],
        name: "matriz7_c",
        image: "",
      },
      {
        geometries: ["matriz7_d_1", "matriz7_d_2"],
        name: "matriz7_d",
        image: "",
      },
      {
        geometries: ["matriz7_e_1", "matriz7_e_2"],
        name: "matriz7_e",
        image: "",
      },
      {
        geometries: ["matriz7_f_1", "matriz7_f_2"],
        name: "matriz7_f",
        image: "",
      },
      {
        geometries: ["matriz7_g_1", "matriz7_g_2"],
        name: "matriz7_g",
        image: "",
      },
      {
        geometries: ["matriz7_h_1", "matriz7_h_2"],
        name: "matriz7_h",
        image: "",
      },
      {
        geometries: ["matriz7_i_1", "matriz7_i_2"],
        name: "matriz7_i",
        image: "",
      },
      {
        geometries: ["matriz7_j_1", "matriz7_j_2"],
        name: "matriz7_j",
        image: "",
      },
      {
        geometries: ["matriz7_k_1", "matriz7_k_2"],
        name: "matriz7_k",
        image: "",
      },
      {
        geometries: ["matriz7_l_1", "matriz7_l_2"],
        name: "matriz7_l",
        image: "",
      },
      {
        geometries: ["matriz7_m_1", "matriz7_m_2"],
        name: "matriz7_m",
        image: "",
      },
      {
        geometries: ["matriz7_n_1", "matriz7_n_2"],
        name: "matriz7_n",
        image: "",
      },
      {
        geometries: ["matriz7_o_1", "matriz7_o_2"],
        name: "matriz7_o",
        image: "",
      },
      {
        geometries: ["matriz7_p_1", "matriz7_p_2"],
        name: "matriz7_p",
        image: "",
      },
      {
        geometries: ["matriz7_q_1", "matriz7_q_2"],
        name: "matriz7_q",
        image: "",
      },
      {
        geometries: ["matriz7_r_1", "matriz7_r_2"],
        name: "matriz7_r",
        image: "",
      },
      {
        geometries: ["matriz7_s_1", "matriz7_s_2"],
        name: "matriz7_s",
        image: "",
      },
      {
        geometries: ["matriz7_t_1", "matriz7_t_2"],
        name: "matriz7_t",
        image: "",
      },
    ],
    image: "",
  },
  8: {
    matrices: [
      {
        geometries: ["matriz8_a_1", "matriz8_a_2"],
        name: "matriz8_a",
        image: "",
      },
      {
        geometries: ["matriz8_b_1", "matriz8_b_2"],
        name: "matriz8_b",
        image: "",
      },
    ],
    image: "",
  },
  9: {
    matrices: [
      {
        geometries: ["matriz9_1_1", "matriz9_1_2"],
        name: "matriz9_1",
        image: "",
      },
      {
        geometries: ["matriz9_2_1", "matriz9_2_2"],
        name: "matriz9_2",
        image: "",
      },
      {
        geometries: ["matriz9_3_1", "matriz9_3_2"],
        name: "matriz9_3",
        image: "",
      },
      {
        geometries: ["matriz9_4_1", "matriz9_4_2"],
        name: "matriz9_4",
        image: "",
      },
      {
        geometries: ["matriz9_5_1", "matriz9_5_2"],
        name: "matriz9_5",
        image: "",
      },
      {
        geometries: ["matriz9_6_1", "matriz9_6_2"],
        name: "matriz9_6",
        image: "",
      },
      {
        geometries: ["matriz9_7_1", "matriz9_7_2"],
        name: "matriz9_7",
        image: "",
      },
      {
        geometries: ["matriz9_8_1", "matriz9_8_2"],
        name: "matriz9_8",
        image: "",
      },
      {
        geometries: ["matriz9_9_1", "matriz9_9_2"],
        name: "matriz9_9",
        image: "",
      },
      {
        geometries: ["matriz9_10_1", "matriz9_10_2"],
        name: "matriz9_10",
        image: "",
      },
      {
        geometries: ["matriz9_11_1", "matriz9_11_2"],
        name: "matriz9_11",
        image: "",
      },
      {
        geometries: ["matriz9_12_1", "matriz9_12_2"],
        name: "matriz9_12",
        image: "",
      },
      {
        geometries: ["matriz9_13_1", "matriz9_13_2"],
        name: "matriz9_13",
        image: "",
      },
      {
        geometries: ["matriz9_14_1", "matriz9_14_2"],
        name: "matriz9_14",
        image: "",
      },
      {
        geometries: ["matriz9_15_1", "matriz9_15_2"],
        name: "matriz9_15",
        image: "",
      },
      {
        geometries: ["matriz9_16_1", "matriz9_16_2"],
        name: "matriz9_16",
        image: "",
      },
      {
        geometries: ["matriz9_17_1", "matriz9_17_2"],
        name: "matriz9_17",
        image: "",
      },
      {
        geometries: ["matriz9_18_1", "matriz9_18_2"],
        name: "matriz9_18",
        image: "",
      },
      {
        geometries: ["matriz9_19_1", "matriz9_19_2"],
        name: "matriz9_19",
        image: "",
      },
      {
        geometries: ["matriz9_20_1", "matriz9_20_2"],
        name: "matriz9_20",
        image: "",
      },
      {
        geometries: ["matriz9_21_1", "matriz9_21_2"],
        name: "matriz9_21",
        image: "",
      },
      {
        geometries: ["matriz9_22_1", "matriz9_22_2"],
        name: "matriz9_22",
        image: "",
      },
      {
        geometries: ["matriz9_23_1", "matriz9_23_2"],
        name: "matriz9_23",
        image: "",
      },
      {
        geometries: ["matriz9_24_1", "matriz9_24_2"],
        name: "matriz9_24",
        image: "",
      },
      {
        geometries: ["matriz9_25_1", "matriz9_25_2"],
        name: "matriz9_25",
        image: "",
      },
      {
        geometries: ["matriz9_26_1", "matriz9_26_2"],
        name: "matriz9_26",
        image: "",
      },
      {
        geometries: ["matriz9_27_1", "matriz9_27_2"],
        name: "matriz9_27",
        image: "",
      },
      {
        geometries: ["matriz9_28_1", "matriz9_28_2"],
        name: "matriz9_28",
        image: "",
      },
      {
        geometries: ["matriz9_29_1", "matriz9_29_2"],
        name: "matriz9_29",
        image: "",
      },
      {
        geometries: ["matriz9_30_1", "matriz9_30_2"],
        name: "matriz9_30",
        image: "",
      },
      {
        geometries: ["matriz9_31_1", "matriz9_31_2"],
        name: "matriz9_31",
        image: "",
      },
      {
        geometries: ["matriz9_32_1", "matriz9_32_2"],
        name: "matriz9_32",
        image: "",
      },
      {
        geometries: ["matriz9_33_1", "matriz9_33_2"],
        name: "matriz9_33",
        image: "",
      },
      {
        geometries: ["matriz9_34_1", "matriz9_34_2"],
        name: "matriz9_34",
        image: "",
      },
      {
        geometries: ["matriz9_35_1", "matriz9_35_2"],
        name: "matriz9_35",
        image: "",
      },
      {
        geometries: ["matriz9_36_1", "matriz9_36_2"],
        name: "matriz9_36",
        image: "",
      },
      {
        geometries: ["matriz9_37_1", "matriz9_37_2"],
        name: "matriz9_37",
        image: "",
      },
      {
        geometries: ["matriz9_38_1", "matriz9_38_2"],
        name: "matriz9_38",
        image: "",
      },
      {
        geometries: ["matriz9_39_1", "matriz9_39_2"],
        name: "matriz9_39",
        image: "",
      },
      {
        geometries: ["matriz9_40_1", "matriz9_40_2"],
        name: "matriz9_40",
        image: "",
      },
    ],
    image: "",
  },
  10: {
    matrices: [
      {
        geometries: ["matriz10_1_1", "matriz10_1_2"],
        name: "matriz10_1",
        image: "",
      },
      {
        geometries: ["matriz10_2_1", "matriz10_2_2"],
        name: "matriz10_2",
        image: "",
      },
    ],
    image: "",
  },
  11: {
    matrices: [
      {
        geometries: ["matriz11_1_1", "matriz11_1_2"],
        name: "matriz11_1",
        image: "",
      },
      {
        geometries: ["matriz11_2_1", "matriz11_2_2"],
        name: "matriz11_2",
        image: "",
      },
      {
        geometries: ["matriz11_3_1", "matriz11_3_2"],
        name: "matriz11_3",
        image: "",
      },
      {
        geometries: ["matriz11_4_1", "matriz11_4_2"],
        name: "matriz11_4",
        image: "",
      },
      {
        geometries: ["matriz11_5_1", "matriz11_5_2"],
        name: "matriz11_5",
        image: "",
      },
      {
        geometries: ["matriz11_6_1", "matriz11_6_2"],
        name: "matriz11_6",
        image: "",
      },
      {
        geometries: ["matriz11_7_1", "matriz11_7_2"],
        name: "matriz11_7",
        image: "",
      },
      {
        geometries: ["matriz11_8_1", "matriz11_8_2"],
        name: "matriz11_8",
        image: "",
      },
      {
        geometries: ["matriz11_9_1", "matriz11_9_2"],
        name: "matriz11_9",
        image: "",
      },
      {
        geometries: ["matriz11_10_1", "matriz11_10_2"],
        name: "matriz11_10",
        image: "",
      },
      {
        geometries: ["matriz11_11_1", "matriz11_11_2"],
        name: "matriz11_11",
        image: "",
      },
      {
        geometries: ["matriz11_12_1", "matriz11_12_2"],
        name: "matriz11_12",
        image: "",
      },
      {
        geometries: ["matriz11_13_1", "matriz11_13_2"],
        name: "matriz11_13",
        image: "",
      },
      {
        geometries: ["matriz11_14_1", "matriz11_14_2"],
        name: "matriz11_14",
        image: "",
      },
      {
        geometries: ["matriz11_15_1", "matriz11_15_2"],
        name: "matriz11_15",
        image: "",
      },
      {
        geometries: ["matriz11_16_1", "matriz11_16_2"],
        name: "matriz11_16",
        image: "",
      },
      {
        geometries: ["matriz11_17_1", "matriz11_17_2"],
        name: "matriz11_17",
        image: "",
      },
      {
        geometries: ["matriz11_18_1", "matriz11_18_2"],
        name: "matriz11_18",
        image: "",
      },
      {
        geometries: ["matriz11_19_1", "matriz11_19_2"],
        name: "matriz11_19",
        image: "",
      },
      {
        geometries: ["matriz11_20_1", "matriz11_20_2"],
        name: "matriz11_20",
        image: "",
      },
      {
        geometries: ["matriz11_21_1", "matriz11_21_2"],
        name: "matriz11_21",
        image: "",
      },
      {
        geometries: ["matriz11_22_1", "matriz11_22_2"],
        name: "matriz11_22",
        image: "",
      },
      {
        geometries: ["matriz11_23_1", "matriz11_23_2"],
        name: "matriz11_23",
        image: "",
      },
      {
        geometries: ["matriz11_24_1", "matriz11_24_2"],
        name: "matriz11_24",
        image: "",
      },
      {
        geometries: ["matriz11_25_1", "matriz11_25_2"],
        name: "matriz11_25",
        image: "",
      },
      {
        geometries: ["matriz11_26_1", "matriz11_26_2"],
        name: "matriz11_26",
        image: "",
      },
      {
        geometries: ["matriz11_27_1", "matriz11_27_2"],
        name: "matriz11_27",
        image: "",
      },
      {
        geometries: ["matriz11_28_1", "matriz11_28_2"],
        name: "matriz11_28",
        image: "",
      },
      {
        geometries: ["matriz11_29_1", "matriz11_29_2"],
        name: "matriz11_29",
        image: "",
      },
      {
        geometries: ["matriz11_30_1", "matriz11_30_2"],
        name: "matriz11_30",
        image: "",
      },
      {
        geometries: ["matriz11_31_1", "matriz11_31_2"],
        name: "matriz11_31",
        image: "",
      },
      {
        geometries: ["matriz11_32_1", "matriz11_32_2"],
        name: "matriz11_32",
        image: "",
      },
      {
        geometries: ["matriz11_33_1", "matriz11_33_2"],
        name: "matriz11_33",
        image: "",
      },
      {
        geometries: ["matriz11_34_1", "matriz11_34_2"],
        name: "matriz11_34",
        image: "",
      },
    ],
    image: "",
  },
  12: {
    matrices: [
      {
        geometries: ["matriz12_1_1", "matriz12_1_2"],
        name: "matriz12_1",
        image: "",
      },
      {
        geometries: ["matriz12_2_1", "matriz12_2_2"],
        name: "matriz12_2",
        image: "",
      },
      {
        geometries: ["matriz12_3_1", "matriz12_3_2"],
        name: "matriz12_3",
        image: "",
      },
      {
        geometries: ["matriz12_4_1", "matriz12_4_2"],
        name: "matriz12_4",
        image: "",
      },
      {
        geometries: ["matriz12_5_1", "matriz12_5_2"],
        name: "matriz12_5",
        image: "",
      },
      {
        geometries: ["matriz12_6_1", "matriz12_6_2"],
        name: "matriz12_6",
        image: "",
      },
      {
        geometries: ["matriz12_7_1", "matriz12_7_2"],
        name: "matriz12_7",
        image: "",
      },
      {
        geometries: ["matriz12_8_1", "matriz12_8_2"],
        name: "matriz12_8",
        image: "",
      },
      {
        geometries: ["matriz12_9_1", "matriz12_9_2"],
        name: "matriz12_9",
        image: "",
      },
      {
        geometries: ["matriz12_10_1", "matriz12_10_2"],
        name: "matriz12_10",
        image: "",
      },
      {
        geometries: ["matriz12_11_1", "matriz12_11_2"],
        name: "matriz12_11",
        image: "",
      },
      {
        geometries: ["matriz12_12_1", "matriz12_12_2"],
        name: "matriz12_12",
        image: "",
      },
      {
        geometries: ["matriz12_13_1", "matriz12_13_2"],
        name: "matriz12_13",
        image: "",
      },
    ],
    image: "",
  },
  13: {
    matrices: [
      {
        geometries: ["matriz13_1_1", "matriz13_1_2"],
        name: "matriz13_1",
        image: "",
      },
      {
        geometries: ["matriz13_2_1", "matriz13_2_2"],
        name: "matriz13_2",
        image: "",
      },
      {
        geometries: ["matriz13_3_1", "matriz13_3_2"],
        name: "matriz13_3",
        image: "",
      },
      {
        geometries: ["matriz13_4_1", "matriz13_4_2"],
        name: "matriz13_4",
        image: "",
      },
    ],
    image: "",
  },
  14: {
    matrices: [
      {
        geometries: ["matriz14_1_1", "matriz14_1_2"],
        name: "matriz14_1",
        image: "",
      },
      {
        geometries: ["matriz14_2_1", "matriz14_2_2"],
        name: "matriz14_2",
        image: "",
      },
    ],
    image: "",
  },
  15: {
    matrices: [
      {
        geometries: ["matriz15_1_1", "matriz15_1_2"],
        name: "matriz15_1",
        image: "",
      },
      {
        geometries: ["matriz15_2_1", "matriz15_2_2"],
        name: "matriz15_2",
        image: "",
      },
      {
        geometries: ["matriz15_3_1", "matriz15_3_2"],
        name: "matriz15_3",
        image: "",
      },
      {
        geometries: ["matriz15_4_1", "matriz15_4_2"],
        name: "matriz15_4",
        image: "",
      },
      {
        geometries: ["matriz15_5_1", "matriz15_5_2"],
        name: "matriz15_5",
        image: "",
      },
      {
        geometries: ["matriz15_5_1", "matriz15_5_2"],
        name: "matriz15_5",
        image: "",
      },
    ],
    image: "",
  },
};
// const categorizedMeshes = {
//   Categoria1: [
//     { mesh: nodes.matriz1_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz1_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz1_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_c_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria2: [
//     { mesh: nodes.matriz2_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_n_2.geometry, material: materials.Aluminio },
//   ],
//   // Agrega más categorías según sea necesario...
//   Categoria3: [
//     { mesh: nodes.matriz3_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria4: [
//     { mesh: nodes.matriz4_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz4_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz4_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz4_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria5: [
//     { mesh: nodes.matriz5_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria6: [
//     { mesh: nodes.matriz6_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz6_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz6_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz6_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria7: [
//     { mesh: nodes.matriz7_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria8: [
//     { mesh: nodes.matriz8_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz8_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz8_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz8_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria9: [
//     { mesh: nodes.matriz9_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_13_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_14_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_14_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_15_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_15_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_16_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_16_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_17_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_17_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_18_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_18_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_19_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_19_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_20_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_20_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_21_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_21_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_22_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_22_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_23_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_23_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_24_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_24_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_25_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_25_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_26_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_26_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_27_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_27_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_28_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_28_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_29_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_29_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_30_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_30_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_31_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_31_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_32_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_32_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_33_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_33_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_34_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_34_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_35_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_35_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_36_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_36_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_37_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_37_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_38_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_38_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_39_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_39_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_40_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_40_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria10: [
//     { mesh: nodes.matriz10_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz10_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz10_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz10_2_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria11: [
//     { mesh: nodes.matriz11_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_13_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_14_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_14_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_15_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_15_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_16_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_16_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_17_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_17_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_18_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_18_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_19_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_19_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_20_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_20_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_21_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_21_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_22_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_22_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_23_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_23_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_24_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_24_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_25_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_25_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_26_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_26_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_27_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_27_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_28_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_28_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_29_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_29_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_30_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_30_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_31_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_31_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_32_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_32_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_33_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_33_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_34_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_34_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria12: [
//     { mesh: nodes.matriz12_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_13_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria13: [
//     { mesh: nodes.matriz13_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_4_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria14: [
//     { mesh: nodes.matriz14_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz14_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz14_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz14_2_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria15: [
//     { mesh: nodes.matriz15_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_6_2.geometry, material: materials.Aluminio },
//   ],
// };

// const meshesToShow = categorizedMeshes[selectedCategory];
