/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MatrixV2.glb --transform -j -s -M 
Files: MatrixV2.glb [834.14KB] > C:\Users\7475\Desktop\Trabajo\Dolc-Modificaciones\public\modelos\Matrix\MatrixV2-transformed.glb [39.36KB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MatrixV2(props) {
  const { nodes, materials } = useGLTF("/modelos/Matrix/MatrixV2-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Pared.geometry} material={nodes.Pared.material} />
      <mesh castShadow geometry={nodes.Balcon_Superior_Suelo.geometry}>
        {/* <shadowMaterial opacity={0.1} transparent={true} /> */}
      </mesh>
      <mesh castShadow geometry={nodes.Balcon_Superior_Tejado.geometry}>
        {/* <shadowMaterial /> */}
      </mesh>
      <mesh castShadow geometry={nodes.Balcon_Inferior_Suelo.geometry}>
        {/* <shadowMaterial /> */}
      </mesh>
      <mesh castShadow geometry={nodes.Balcon_Inferior_Tejado.geometry}>
        {/* <shadowMaterial /> */}
      </mesh>
      <mesh castShadow geometry={nodes.Cristales.geometry}>
        {/* <shadowMaterial /> */}
      </mesh>
      {/* <mesh castShadow receiveShadow geometry={nodes.Suelo.geometry} material={nodes.Suelo.material} /> */}
    </group>
  );
}

// useGLTF.preload("/MatrixV2-transformed.glb");
