import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";

// Definir las categorías y las mallas correspondientes
const categorizedMeshes = {
  Categoria1: [
    { mesh: nodes.matriz1_a_1, material: materials.Base },
    { mesh: nodes.matriz1_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz1_b_1, material: materials.Base },
    { mesh: nodes.matriz1_b_2, material: materials.Aluminio },
    { mesh: nodes.matriz1_c_1, material: materials.Base },
    { mesh: nodes.matriz1_c_2, material: materials.Aluminio },
  ],
  Categoria2: [
    { mesh: nodes.matriz2_a_1, material: materials.Base },
    { mesh: nodes.matriz2_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_b_1, material: materials.Base },
    { mesh: nodes.matriz2_b_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_c_1, material: materials.Base },
    { mesh: nodes.matriz2_c_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_d_1, material: materials.Base },
    { mesh: nodes.matriz2_d_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_e_1, material: materials.Base },
    { mesh: nodes.matriz2_e_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_f_1, material: materials.Base },
    { mesh: nodes.matriz2_f_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_g_1, material: materials.Base },
    { mesh: nodes.matriz2_g_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_h_1, material: materials.Base },
    { mesh: nodes.matriz2_h_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_i_1, material: materials.Base },
    { mesh: nodes.matriz2_i_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_j_1, material: materials.Base },
    { mesh: nodes.matriz2_j_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_k_1, material: materials.Base },
    { mesh: nodes.matriz2_k_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_l_1, material: materials.Base },
    { mesh: nodes.matriz2_l_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_m_1, material: materials.Base },
    { mesh: nodes.matriz2_m_2, material: materials.Aluminio },
    { mesh: nodes.matriz2_n_1, material: materials.Base },
    { mesh: nodes.matriz2_n_2, material: materials.Aluminio },
  ],
  // Agrega más categorías según sea necesario...
  Categoria3: [
    { mesh: nodes.matriz3_a_1, material: materials.Base },
    { mesh: nodes.matriz3_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_b_1, material: materials.Base },
    { mesh: nodes.matriz3_b_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_c_1, material: materials.Base },
    { mesh: nodes.matriz3_c_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_d_1, material: materials.Base },
    { mesh: nodes.matriz3_d_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_e_1, material: materials.Base },
    { mesh: nodes.matriz3_e_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_f_1, material: materials.Base },
    { mesh: nodes.matriz3_f_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_g_1, material: materials.Base },
    { mesh: nodes.matriz3_g_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_h_1, material: materials.Base },
    { mesh: nodes.matriz3_h_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_i_1, material: materials.Base },
    { mesh: nodes.matriz3_i_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_j_1, material: materials.Base },
    { mesh: nodes.matriz3_j_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_k_1, material: materials.Base },
    { mesh: nodes.matriz3_k_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_l_1, material: materials.Base },
    { mesh: nodes.matriz3_l_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_m_1, material: materials.Base },
    { mesh: nodes.matriz3_m_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_n_1, material: materials.Base },
    { mesh: nodes.matriz3_n_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_o_1, material: materials.Base },
    { mesh: nodes.matriz3_o_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_p_1, material: materials.Base },
    { mesh: nodes.matriz3_p_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_q_1, material: materials.Base },
    { mesh: nodes.matriz3_q_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_r_1, material: materials.Base },
    { mesh: nodes.matriz3_r_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_s_1, material: materials.Base },
    { mesh: nodes.matriz3_s_2, material: materials.Aluminio },
    { mesh: nodes.matriz3_t_1, material: materials.Base },
    { mesh: nodes.matriz3_t_2, material: materials.Aluminio },
  ],
  Categoria4: [
    { mesh: nodes.matriz4_a_1, material: materials.Base },
    { mesh: nodes.matriz4_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz4_b_1, material: materials.Base },
    { mesh: nodes.matriz4_b_2, material: materials.Aluminio },
  ],
  Categoria5: [
    { mesh: nodes.matriz5_a_1, material: materials.Base },
    { mesh: nodes.matriz5_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_b_1, material: materials.Base },
    { mesh: nodes.matriz5_b_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_c_1, material: materials.Base },
    { mesh: nodes.matriz5_c_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_d_1, material: materials.Base },
    { mesh: nodes.matriz5_d_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_e_1, material: materials.Base },
    { mesh: nodes.matriz5_e_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_f_1, material: materials.Base },
    { mesh: nodes.matriz5_f_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_g_1, material: materials.Base },
    { mesh: nodes.matriz5_g_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_h_1, material: materials.Base },
    { mesh: nodes.matriz5_h_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_i_1, material: materials.Base },
    { mesh: nodes.matriz5_i_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_j_1, material: materials.Base },
    { mesh: nodes.matriz5_j_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_k_1, material: materials.Base },
    { mesh: nodes.matriz5_k_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_l_1, material: materials.Base },
    { mesh: nodes.matriz5_l_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_m_1, material: materials.Base },
    { mesh: nodes.matriz5_m_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_n_1, material: materials.Base },
    { mesh: nodes.matriz5_n_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_o_1, material: materials.Base },
    { mesh: nodes.matriz5_o_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_p_1, material: materials.Base },
    { mesh: nodes.matriz5_p_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_q_1, material: materials.Base },
    { mesh: nodes.matriz5_q_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_r_1, material: materials.Base },
    { mesh: nodes.matriz5_r_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_s_1, material: materials.Base },
    { mesh: nodes.matriz5_s_2, material: materials.Aluminio },
    { mesh: nodes.matriz5_t_1, material: materials.Base },
    { mesh: nodes.matriz5_t_2, material: materials.Aluminio },
  ],
  Categoria6: [
    { mesh: nodes.matriz6_a_1, material: materials.Base },
    { mesh: nodes.matriz6_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz6_b_1, material: materials.Base },
    { mesh: nodes.matriz6_b_2, material: materials.Aluminio },
  ],
  Categoria7: [
    { mesh: nodes.matriz7_a_1, material: materials.Base },
    { mesh: nodes.matriz7_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_b_1, material: materials.Base },
    { mesh: nodes.matriz7_b_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_c_1, material: materials.Base },
    { mesh: nodes.matriz7_c_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_d_1, material: materials.Base },
    { mesh: nodes.matriz7_d_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_e_1, material: materials.Base },
    { mesh: nodes.matriz7_e_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_f_1, material: materials.Base },
    { mesh: nodes.matriz7_f_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_g_1, material: materials.Base },
    { mesh: nodes.matriz7_g_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_h_1, material: materials.Base },
    { mesh: nodes.matriz7_h_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_i_1, material: materials.Base },
    { mesh: nodes.matriz7_i_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_j_1, material: materials.Base },
    { mesh: nodes.matriz7_j_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_k_1, material: materials.Base },
    { mesh: nodes.matriz7_k_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_l_1, material: materials.Base },
    { mesh: nodes.matriz7_l_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_m_1, material: materials.Base },
    { mesh: nodes.matriz7_m_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_n_1, material: materials.Base },
    { mesh: nodes.matriz7_n_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_o_1, material: materials.Base },
    { mesh: nodes.matriz7_o_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_p_1, material: materials.Base },
    { mesh: nodes.matriz7_p_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_q_1, material: materials.Base },
    { mesh: nodes.matriz7_q_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_r_1, material: materials.Base },
    { mesh: nodes.matriz7_r_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_s_1, material: materials.Base },
    { mesh: nodes.matriz7_s_2, material: materials.Aluminio },
    { mesh: nodes.matriz7_t_1, material: materials.Base },
    { mesh: nodes.matriz7_t_2, material: materials.Aluminio },
  ],
  Categoria8: [
    { mesh: nodes.matriz8_a_1, material: materials.Base },
    { mesh: nodes.matriz8_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz8_b_1, material: materials.Base },
    { mesh: nodes.matriz8_b_2, material: materials.Aluminio },
  ],
  Categoria9: [
    { mesh: nodes.matriz9_1_1, material: materials.Base },
    { mesh: nodes.matriz9_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_2_1, material: materials.Base },
    { mesh: nodes.matriz9_2_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_3_1, material: materials.Base },
    { mesh: nodes.matriz9_3_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_4_1, material: materials.Base },
    { mesh: nodes.matriz9_4_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_5_1, material: materials.Base },
    { mesh: nodes.matriz9_5_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_6_1, material: materials.Base },
    { mesh: nodes.matriz9_6_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_7_1, material: materials.Base },
    { mesh: nodes.matriz9_7_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_8_1, material: materials.Base },
    { mesh: nodes.matriz9_8_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_9_1, material: materials.Base },
    { mesh: nodes.matriz9_9_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_10_1, material: materials.Base },
    { mesh: nodes.matriz9_10_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_11_1, material: materials.Base },
    { mesh: nodes.matriz9_11_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_12_1, material: materials.Base },
    { mesh: nodes.matriz9_12_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_13_1, material: materials.Base },
    { mesh: nodes.matriz9_13_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_14_1, material: materials.Base },
    { mesh: nodes.matriz9_14_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_15_1, material: materials.Base },
    { mesh: nodes.matriz9_15_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_16_1, material: materials.Base },
    { mesh: nodes.matriz9_16_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_17_1, material: materials.Base },
    { mesh: nodes.matriz9_17_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_18_1, material: materials.Base },
    { mesh: nodes.matriz9_18_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_19_1, material: materials.Base },
    { mesh: nodes.matriz9_19_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_20_1, material: materials.Base },
    { mesh: nodes.matriz9_20_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_21_1, material: materials.Base },
    { mesh: nodes.matriz9_21_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_22_1, material: materials.Base },
    { mesh: nodes.matriz9_22_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_23_1, material: materials.Base },
    { mesh: nodes.matriz9_23_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_24_1, material: materials.Base },
    { mesh: nodes.matriz9_24_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_25_1, material: materials.Base },
    { mesh: nodes.matriz9_25_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_26_1, material: materials.Base },
    { mesh: nodes.matriz9_26_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_27_1, material: materials.Base },
    { mesh: nodes.matriz9_27_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_28_1, material: materials.Base },
    { mesh: nodes.matriz9_28_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_29_1, material: materials.Base },
    { mesh: nodes.matriz9_29_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_30_1, material: materials.Base },
    { mesh: nodes.matriz9_30_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_31_1, material: materials.Base },
    { mesh: nodes.matriz9_31_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_32_1, material: materials.Base },
    { mesh: nodes.matriz9_32_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_33_1, material: materials.Base },
    { mesh: nodes.matriz9_33_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_34_1, material: materials.Base },
    { mesh: nodes.matriz9_34_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_35_1, material: materials.Base },
    { mesh: nodes.matriz9_35_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_36_1, material: materials.Base },
    { mesh: nodes.matriz9_36_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_37_1, material: materials.Base },
    { mesh: nodes.matriz9_37_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_38_1, material: materials.Base },
    { mesh: nodes.matriz9_38_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_39_1, material: materials.Base },
    { mesh: nodes.matriz9_39_2, material: materials.Aluminio },
    { mesh: nodes.matriz9_40_1, material: materials.Base },
    { mesh: nodes.matriz9_40_2, material: materials.Aluminio },
  ],
  Categoria10: [
    { mesh: nodes.matriz10_a_1, material: materials.Base },
    { mesh: nodes.matriz10_a_2, material: materials.Aluminio },
    { mesh: nodes.matriz10_b_1, material: materials.Base },
    { mesh: nodes.matriz10_b_2, material: materials.Aluminio },
  ],
  Categoria11: [
    { mesh: nodes.matriz11_1_1, material: materials.Base },
    { mesh: nodes.matriz11_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_2_1, material: materials.Base },
    { mesh: nodes.matriz11_2_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_3_1, material: materials.Base },
    { mesh: nodes.matriz11_3_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_4_1, material: materials.Base },
    { mesh: nodes.matriz11_4_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_5_1, material: materials.Base },
    { mesh: nodes.matriz11_5_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_6_1, material: materials.Base },
    { mesh: nodes.matriz11_6_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_7_1, material: materials.Base },
    { mesh: nodes.matriz11_7_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_8_1, material: materials.Base },
    { mesh: nodes.matriz11_8_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_9_1, material: materials.Base },
    { mesh: nodes.matriz11_9_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_10_1, material: materials.Base },
    { mesh: nodes.matriz11_10_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_11_1, material: materials.Base },
    { mesh: nodes.matriz11_11_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_12_1, material: materials.Base },
    { mesh: nodes.matriz11_12_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_13_1, material: materials.Base },
    { mesh: nodes.matriz11_13_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_14_1, material: materials.Base },
    { mesh: nodes.matriz11_14_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_15_1, material: materials.Base },
    { mesh: nodes.matriz11_15_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_16_1, material: materials.Base },
    { mesh: nodes.matriz11_16_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_17_1, material: materials.Base },
    { mesh: nodes.matriz11_17_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_18_1, material: materials.Base },
    { mesh: nodes.matriz11_18_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_19_1, material: materials.Base },
    { mesh: nodes.matriz11_19_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_20_1, material: materials.Base },
    { mesh: nodes.matriz11_20_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_21_1, material: materials.Base },
    { mesh: nodes.matriz11_21_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_22_1, material: materials.Base },
    { mesh: nodes.matriz11_22_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_23_1, material: materials.Base },
    { mesh: nodes.matriz11_23_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_24_1, material: materials.Base },
    { mesh: nodes.matriz11_24_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_25_1, material: materials.Base },
    { mesh: nodes.matriz11_25_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_26_1, material: materials.Base },
    { mesh: nodes.matriz11_26_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_27_1, material: materials.Base },
    { mesh: nodes.matriz11_27_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_28_1, material: materials.Base },
    { mesh: nodes.matriz11_28_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_29_1, material: materials.Base },
    { mesh: nodes.matriz11_29_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_30_1, material: materials.Base },
    { mesh: nodes.matriz11_30_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_31_1, material: materials.Base },
    { mesh: nodes.matriz11_31_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_32_1, material: materials.Base },
    { mesh: nodes.matriz11_32_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_33_1, material: materials.Base },
    { mesh: nodes.matriz11_33_2, material: materials.Aluminio },
    { mesh: nodes.matriz11_34_1, material: materials.Base },
    { mesh: nodes.matriz11_34_2, material: materials.Aluminio },
  ],
  Categoria12: [
    { mesh: nodes.matriz12_1_1, material: materials.Base },
    { mesh: nodes.matriz12_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_2_1, material: materials.Base },
    { mesh: nodes.matriz12_2_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_3_1, material: materials.Base },
    { mesh: nodes.matriz12_3_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_4_1, material: materials.Base },
    { mesh: nodes.matriz12_4_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_5_1, material: materials.Base },
    { mesh: nodes.matriz12_5_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_6_1, material: materials.Base },
    { mesh: nodes.matriz12_6_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_7_1, material: materials.Base },
    { mesh: nodes.matriz12_7_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_8_1, material: materials.Base },
    { mesh: nodes.matriz12_8_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_9_1, material: materials.Base },
    { mesh: nodes.matriz12_9_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_10_1, material: materials.Base },
    { mesh: nodes.matriz12_10_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_11_1, material: materials.Base },
    { mesh: nodes.matriz12_11_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_12_1, material: materials.Base },
    { mesh: nodes.matriz12_12_2, material: materials.Aluminio },
    { mesh: nodes.matriz12_13_1, material: materials.Base },
    { mesh: nodes.matriz12_13_2, material: materials.Aluminio },
  ],
  Categoria13: [
    { mesh: nodes.matriz13_1_1, material: materials.Base },
    { mesh: nodes.matriz13_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz13_2_1, material: materials.Base },
    { mesh: nodes.matriz13_2_2, material: materials.Aluminio },
    { mesh: nodes.matriz13_3_1, material: materials.Base },
    { mesh: nodes.matriz13_3_2, material: materials.Aluminio },
    { mesh: nodes.matriz13_4_1, material: materials.Base },
    { mesh: nodes.matriz13_4_2, material: materials.Aluminio },
  ],
  Categoria14: [
    { mesh: nodes.matriz14_1_1, material: materials.Base },
    { mesh: nodes.matriz14_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz14_2_1, material: materials.Base },
    { mesh: nodes.matriz14_2_2, material: materials.Aluminio },
  ],
  Categoria15: [
    { mesh: nodes.matriz15_1_1, material: materials.Base },
    { mesh: nodes.matriz15_1_2, material: materials.Aluminio },
    { mesh: nodes.matriz15_2_1, material: materials.Base },
    { mesh: nodes.matriz15_2_2, material: materials.Aluminio },
    { mesh: nodes.matriz15_3_1, material: materials.Base },
    { mesh: nodes.matriz15_3_2, material: materials.Aluminio },
    { mesh: nodes.matriz15_4_1, material: materials.Base },
    { mesh: nodes.matriz15_4_2, material: materials.Aluminio },
    { mesh: nodes.matriz15_5_1, material: materials.Base },
    { mesh: nodes.matriz15_5_2, material: materials.Aluminio },
    { mesh: nodes.matriz15_6_1, material: materials.Base },
    { mesh: nodes.matriz15_6_2, material: materials.Aluminio },
  ],
};

export function Modelo(props) {
  const { nodes, materials } = useGLTF("/modelos/MatrixRotador.glb");
  const [selectedCategory, setSelectedCategory] = useState("Categoria1"); // Categoría inicial
  const [selectedMaterial, setSelectedMaterial] = useState(materials.Base); // Material inicial

  const meshesToShow = categorizedMeshes[selectedCategory];

  return (
    <group {...props} dispose={null}>
      {meshesToShow.map((entry, index) => (
        <mesh
          key={index}
          geometry={entry.mesh.geometry}
          material={selectedMaterial}
          position={entry.mesh.position}
          scale={entry.mesh.scale}
        />
      ))}
    </group>
  );
}

// Preload del modelo para optimización
useGLTF.preload("/modelos/MatrixRotador.glb");

