/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 EscenaTXT.glb --transform 
Files: EscenaTXT.glb [6.36MB] > C:\Users\7475\Desktop\Trabajo\Dolc-Modificaciones\public\EscenaTXT-transformed.glb [492.42KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EscenaTXT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PIEZA_001.geometry} material={materials.Pieza01} />
      <mesh geometry={nodes.PIEZA_002.geometry} material={materials.Pieza02} />
      <mesh geometry={nodes.PIEZA_003.geometry} material={materials.Pieza03} />
      <mesh geometry={nodes.PIEZA_004.geometry} material={materials.Pieza04} />
      <mesh geometry={nodes.PIEZA_005.geometry} material={materials.Pieza05} />
      <mesh geometry={nodes.PIEZA_006.geometry} material={materials.Pieza06} />
      <mesh geometry={nodes.PIEZA_007.geometry} material={materials.Pieza07} />
      <mesh geometry={nodes.PIEZA_008.geometry} material={materials.Pieza08} />
      <mesh geometry={nodes.PIEZA_009.geometry} material={materials.Pieza09} />
      <mesh geometry={nodes.PIEZA_010.geometry} material={materials.Pieza10} />
      <mesh geometry={nodes.PIEZA_011.geometry} material={materials.Pieza11} />
      <mesh geometry={nodes.PIEZA_012.geometry} material={materials.Pieza18} />
      <mesh geometry={nodes.PIEZA_014.geometry} material={materials.Pieza17} />
      <mesh geometry={nodes.PIEZA_017.geometry} material={materials.Pieza12} />
      <mesh geometry={nodes.PIEZA_018.geometry} material={materials.Pieza13} />
      <mesh geometry={nodes.PIEZA_019.geometry} material={materials.Pieza14} />
      <mesh geometry={nodes.PIEZA_020.geometry} material={materials.Pieza15} />
      <mesh geometry={nodes.PIEZA_021.geometry} material={materials.Pieza16} />
      <mesh geometry={nodes.PERFIL_001.geometry} material={materials.Aluminio} />
      <mesh geometry={nodes.CARCASA_EDIFICIO.geometry} material={materials.Fondo} />
      <mesh geometry={nodes.CRISTALES_BARANDILLAS.geometry} material={materials.Cristal} />
      <mesh geometry={nodes.LUCECITAS.geometry} material={nodes.LUCECITAS.material} />
      <mesh geometry={nodes.VENTANAS.geometry} material={materials.Marco_Ventana} />
    </group>
  )
}

useGLTF.preload('/EscenaTXT-transformed.glb')
