export { default as Introduccion } from './System/01_Introduccion'
export { default as Indice } from './System/02_Indice'
export { default as Dolcker } from './System/03_Dolcker'
export { default as Ventajas } from './System/04_Ventajas'
export { default as Aplicaciones } from './System/05_Aplicaciones'
export { default as Disenos } from './System/06_Diseno'
export { default as Caracteristicas } from './System/07_Caracteristicas'
export { default as Sistemas } from './System/08_Sistemas'
export { default as Descargas } from './System/09_Descargas'
export { default as Final } from './System/10_Final'
export { default as Galeria } from './System/11_Galeria'
//TLINE
export { default as IndiceTline } from './Tline/01_Inicio'
export { default as DolckerTline } from './Tline/02_Dolcker'
export { default as VentajasTline } from './Tline/03_Ventajas'
export { default as AplicacionesTline } from './Tline/04_Aplicaciones'
export { default as DisenosTline } from './Tline/05_Diseno'
export { default as CaracteristicasTline } from './Tline/06_Caracteristicas'
export { default as SistemasTline } from './Tline/07_Sistemas'
export { default as DescargasTline } from './Tline/08_Descargas'

