export const Mallas = {
  matriz1_a: {
    geometries: ["matriz1_a_1", "matriz1_a_2"],
    name: "matriz1_a",
    image: "",
  },
  matriz1_b: {
    geometries: ["matriz1_b_1", "matriz1_b_2"],
    name: "matriz1_b",
    image: "",
  },
  matriz1_c: {
    geometries: ["matriz1_c_1", "matriz1_c_2"],
    name: "matriz1_c",
    image: "",
  },
  matriz2_a: {
    geometries: ["matriz2_a_1", "matriz2_a_2"],
    name: "matriz2_a",
    image: "",
  },
  matriz2_b: {
    geometries: ["matriz2_b_1", "matriz2_b_2"],
    name: "matriz2_b",
    image: "",
  },
  matriz2_c: {
    geometries: ["matriz2_c_1", "matriz2_c_2"],
    name: "matriz2_c",
    image: "",
  },
  matriz2_d: {
    geometries: ["matriz2_d_1", "matriz2_d_2"],
    name: "matriz2_d",
    image: "",
  },
  matriz2_e: {
    geometries: ["matriz2_e_1", "matriz2_e_2"],
    name: "matriz2_e",
    image: "",
  },
  matriz2_f: {
    geometries: ["matriz2_f_1", "matriz2_f_2"],
    name: "matriz2_f",
    image: "",
  },
  matriz2_g: {
    geometries: ["matriz2_g_1", "matriz2_g_2"],
    name: "matriz2_g",
    image: "",
  },
  matriz2_h: {
    geometries: ["matriz2_h_1", "matriz2_h_2"],
    name: "matriz2_h",
    image: "",
  },
  matriz2_i: {
    geometries: ["matriz2_i_1", "matriz2_i_2"],
    name: "matriz2_i",
    image: "",
  },
  matriz2_j: {
    geometries: ["matriz2_j_1", "matriz2_j_2"],
    name: "matriz2_j",
    image: "",
  },
  matriz2_k: {
    geometries: ["matriz2_k_1", "matriz2_k_2"],
    name: "matriz2_k",
    image: "",
  },
  matriz2_l: {
    geometries: ["matriz2_l_1", "matriz2_l_2"],
    name: "matriz2_l",
    image: "",
  },
  matriz2_m: {
    geometries: ["matriz2_m_1", "matriz2_m_2"],
    name: "matriz2_m",
    image: "",
  },
  matriz2_n: {
    geometries: ["matriz2_n_1", "matriz2_n_2"],
    name: "matriz2_n",
    image: "",
  },
  matriz3_a: {
    geometries: ["matriz3_a_1", "matriz3_a_2"],
    name: "matriz3_a",
    image: "",
  },
  matriz3_b: {
    geometries: ["matriz3_b_1", "matriz3_b_2"],
    name: "matriz3_b",
    image: "",
  },
  matriz3_c: {
    geometries: ["matriz3_c_1", "matriz3_c_2"],
    name: "matriz3_c",
    image: "",
  },
  matriz3_d: {
    geometries: ["matriz3_d_1", "matriz3_d_2"],
    name: "matriz3_d",
    image: "",
  },
  matriz3_e: {
    geometries: ["matriz3_e_1", "matriz3_e_2"],
    name: "matriz3_e",
    image: "",
  },
  matriz3_f: {
    geometries: ["matriz3_f_1", "matriz3_f_2"],
    name: "matriz3_f",
    image: "",
  },
  matriz3_g: {
    geometries: ["matriz3_g_1", "matriz3_g_2"],
    name: "matriz3_g",
    image: "",
  },
  matriz3_h: {
    geometries: ["matriz3_h_1", "matriz3_h_2"],
    name: "matriz3_h",
    image: "",
  },
  matriz3_i: {
    geometries: ["matriz3_i_1", "matriz3_i_2"],
    name: "matriz3_i",
    image: "",
  },
  matriz3_j: {
    geometries: ["matriz3_j_1", "matriz3_j_2"],
    name: "matriz3_j",
    image: "",
  },
  matriz3_k: {
    geometries: ["matriz3_k_1", "matriz3_k_2"],
    name: "matriz3_k",
    image: "",
  },
  matriz3_l: {
    geometries: ["matriz3_l_1", "matriz3_l_2"],
    name: "matriz3_l",
    image: "",
  },
  matriz3_m: {
    geometries: ["matriz3_m_1", "matriz3_m_2"],
    name: "matriz3_m",
    image: "",
  },
  matriz3_n: {
    geometries: ["matriz3_n_1", "matriz3_n_2"],
    name: "matriz3_n",
    image: "",
  },
  matriz3_o: {
    geometries: ["matriz3_o_1", "matriz3_o_2"],
    name: "matriz3_o",
    image: "",
  },
  matriz3_p: {
    geometries: ["matriz3_p_1", "matriz3_p_2"],
    name: "matriz3_p",
    image: "",
  },
  matriz3_q: {
    geometries: ["matriz3_q_1", "matriz3_q_2"],
    name: "matriz3_q",
    image: "",
  },
  matriz3_r: {
    geometries: ["matriz3_r_1", "matriz3_r_2"],
    name: "matriz3_r",
    image: "",
  },
  matriz3_s: {
    geometries: ["matriz3_s_1", "matriz3_s_2"],
    name: "matriz3_s",
    image: "",
  },
  matriz3_t: {
    geometries: ["matriz3_t_1", "matriz3_t_2"],
    name: "matriz3_t",
    image: "",
  },
  matriz4_a: {
    geometries: ["matriz4_a_1", "matriz4_a_2"],
    name: "matriz4_a",
    image: "",
  },
  matriz5_a: {
    geometries: ["matriz5_a_1", "matriz5_a_2"],
    name: "matriz5_a",
    image: "",
  },
  matriz5_b: {
    geometries: ["matriz5_b_1", "matriz5_b_2"],
    name: "matriz5_b",
    image: "",
  },
  matriz5_c: {
    geometries: ["matriz5_c_1", "matriz5_c_2"],
    name: "matriz5_c",
    image: "",
  },
  matriz5_d: {
    geometries: ["matriz5_d_1", "matriz5_d_2"],
    name: "matriz5_d",
    image: "",
  },
  matriz5_e: {
    geometries: ["matriz5_e_1", "matriz5_e_2"],
    name: "matriz5_e",
    image: "",
  },
  matriz5_f: {
    geometries: ["matriz5_f_1", "matriz5_f_2"],
    name: "matriz5_f",
    image: "",
  },
  matriz5_g: {
    geometries: ["matriz5_g_1", "matriz5_g_2"],
    name: "matriz5_g",
    image: "",
  },
  matriz5_h: {
    geometries: ["matriz5_h_1", "matriz5_h_2"],
    name: "matriz5_h",
    image: "",
  },
  matriz5_i: {
    geometries: ["matriz5_i_1", "matriz5_i_2"],
    name: "matriz5_i",
    image: "",
  },
  matriz5_j: {
    geometries: ["matriz5_j_1", "matriz5_j_2"],
    name: "matriz5_j",
    image: "",
  },
  matriz5_k: {
    geometries: ["matriz5_k_1", "matriz5_k_2"],
    name: "matriz5_k",
    image: "",
  },
  matriz5_l: {
    geometries: ["matriz5_l_1", "matriz5_l_2"],
    name: "matriz5_l",
    image: "",
  },
  matriz5_m: {
    geometries: ["matriz5_m_1", "matriz5_m_2"],
    name: "matriz5_m",
    image: "",
  },
  matriz5_n: {
    geometries: ["matriz5_n_1", "matriz5_n_2"],
    name: "matriz5_n",
    image: "",
  },
  matriz5_o: {
    geometries: ["matriz5_o_1", "matriz5_o_2"],
    name: "matriz5_o",
    image: "",
  },
  matriz5_p: {
    geometries: ["matriz5_p_1", "matriz5_p_2"],
    name: "matriz5_p",
    image: "",
  },
  matriz5_q: {
    geometries: ["matriz5_q_1", "matriz5_q_2"],
    name: "matriz5_q",
    image: "",
  },
  matriz5_r: {
    geometries: ["matriz5_r_1", "matriz5_r_2"],
    name: "matriz5_r",
    image: "",
  },
  matriz5_s: {
    geometries: ["matriz5_s_1", "matriz5_s_2"],
    name: "matriz5_s",
    image: "",
  },
  matriz5_t: {
    geometries: ["matriz5_t_1", "matriz5_t_2"],
    name: "matriz5_t",
    image: "",
  },
  matriz6_a: {
    geometries: ["matriz6_a_1", "matriz6_a_2"],
    name: "matriz6_a",
    image: "",
  },
  matriz6_b: {
    geometries: ["matriz6_b_1", "matriz6_b_2"],
    name: "matriz6_b",
    image: "",
  },
  matriz7_a: {
    geometries: ["matriz7_a_1", "matriz7_a_2"],
    name: "matriz7_a",
    image: "",
  },
  matriz7_b: {
    geometries: ["matriz7_b_1", "matriz7_b_2"],
    name: "matriz7_b",
    image: "",
  },
  matriz7_c: {
    geometries: ["matriz7_c_1", "matriz7_c_2"],
    name: "matriz7_c",
    image: "",
  },
  matriz7_d: {
    geometries: ["matriz7_d_1", "matriz7_d_2"],
    name: "matriz7_d",
    image: "",
  },
  matriz7_e: {
    geometries: ["matriz7_e_1", "matriz7_e_2"],
    name: "matriz7_e",
    image: "",
  },
  matriz7_f: {
    geometries: ["matriz7_f_1", "matriz7_f_2"],
    name: "matriz7_f",
    image: "",
  },
  matriz7_g: {
    geometries: ["matriz7_g_1", "matriz7_g_2"],
    name: "matriz7_g",
    image: "",
  },
  matriz7_h: {
    geometries: ["matriz7_h_1", "matriz7_h_2"],
    name: "matriz7_h",
    image: "",
  },
  matriz7_i: {
    geometries: ["matriz7_i_1", "matriz7_i_2"],
    name: "matriz7_i",
    image: "",
  },
  matriz7_j: {
    geometries: ["matriz7_j_1", "matriz7_j_2"],
    name: "matriz7_j",
    image: "",
  },
  matriz7_k: {
    geometries: ["matriz7_k_1", "matriz7_k_2"],
    name: "matriz7_k",
    image: "",
  },
  matriz7_l: {
    geometries: ["matriz7_l_1", "matriz7_l_2"],
    name: "matriz7_l",
    image: "",
  },
  matriz7_m: {
    geometries: ["matriz7_m_1", "matriz7_m_2"],
    name: "matriz7_m",
    image: "",
  },
  matriz7_n: {
    geometries: ["matriz7_n_1", "matriz7_n_2"],
    name: "matriz7_n",
    image: "",
  },
  matriz7_o: {
    geometries: ["matriz7_o_1", "matriz7_o_2"],
    name: "matriz7_o",
    image: "",
  },
  matriz7_p: {
    geometries: ["matriz7_p_1", "matriz7_p_2"],
    name: "matriz7_p",
    image: "",
  },
  matriz7_q: {
    geometries: ["matriz7_q_1", "matriz7_q_2"],
    name: "matriz7_q",
    image: "",
  },
  matriz7_r: {
    geometries: ["matriz7_r_1", "matriz7_r_2"],
    name: "matriz7_r",
    image: "",
  },
  matriz7_s: {
    geometries: ["matriz7_s_1", "matriz7_s_2"],
    name: "matriz7_s",
    image: "",
  },
  matriz7_t: {
    geometries: ["matriz7_t_1", "matriz7_t_2"],
    name: "matriz7_t",
    image: "",
  },
  matriz8_a: {
    geometries: ["matriz8_a_1", "matriz8_a_2"],
    name: "matriz8_a",
    image: "",
  },
  matriz8_b: {
    geometries: ["matriz8_b_1", "matriz8_b_2"],
    name: "matriz8_b",
    image: "",
  },
  matriz9_1: {
    geometries: ["matriz9_1_1", "matriz9_1_2"],
    name: "matriz9_1",
    image: "",
  },
  matriz9_2: {
    geometries: ["matriz9_2_1", "matriz9_2_2"],
    name: "matriz9_2",
    image: "",
  },
  matriz9_3: {
    geometries: ["matriz9_3_1", "matriz9_3_2"],
    name: "matriz9_3",
    image: "",
  },
  matriz9_4: {
    geometries: ["matriz9_4_1", "matriz9_4_2"],
    name: "matriz9_4",
    image: "",
  },
  matriz9_5: {
    geometries: ["matriz9_5_1", "matriz9_5_2"],
    name: "matriz9_5",
    image: "",
  },
  matriz9_6: {
    geometries: ["matriz9_6_1", "matriz9_6_2"],
    name: "matriz9_6",
    image: "",
  },
  matriz9_7: {
    geometries: ["matriz9_7_1", "matriz9_7_2"],
    name: "matriz9_7",
    image: "",
  },
  matriz9_8: {
    geometries: ["matriz9_8_1", "matriz9_8_2"],
    name: "matriz9_8",
    image: "",
  },
  matriz9_9: {
    geometries: ["matriz9_9_1", "matriz9_9_2"],
    name: "matriz9_9",
    image: "",
  },
  matriz9_10: {
    geometries: ["matriz9_10_1", "matriz9_10_2"],
    name: "matriz9_10",
    image: "",
  },
  matriz9_11: {
    geometries: ["matriz9_11_1", "matriz9_11_2"],
    name: "matriz9_11",
    image: "",
  },
  matriz9_12: {
    geometries: ["matriz9_12_1", "matriz9_12_2"],
    name: "matriz9_12",
    image: "",
  },
  matriz9_13: {
    geometries: ["matriz9_13_1", "matriz9_13_2"],
    name: "matriz9_13",
    image: "",
  },
  matriz9_14: {
    geometries: ["matriz9_14_1", "matriz9_14_2"],
    name: "matriz9_14",
    image: "",
  },
  matriz9_15: {
    geometries: ["matriz9_15_1", "matriz9_15_2"],
    name: "matriz9_15",
    image: "",
  },
  matriz9_16: {
    geometries: ["matriz9_16_1", "matriz9_16_2"],
    name: "matriz9_16",
    image: "",
  },
  matriz9_17: {
    geometries: ["matriz9_17_1", "matriz9_17_2"],
    name: "matriz9_17",
    image: "",
  },
  matriz9_18: {
    geometries: ["matriz9_18_1", "matriz9_18_2"],
    name: "matriz9_18",
    image: "",
  },
  matriz9_19: {
    geometries: ["matriz9_19_1", "matriz9_19_2"],
    name: "matriz9_19",
    image: "",
  },
  matriz9_20: {
    geometries: ["matriz9_20_1", "matriz9_20_2"],
    name: "matriz9_20",
    image: "",
  },
  matriz9_21: {
    geometries: ["matriz9_21_1", "matriz9_21_2"],
    name: "matriz9_21",
    image: "",
  },
  matriz9_22: {
    geometries: ["matriz9_22_1", "matriz9_22_2"],
    name: "matriz9_22",
    image: "",
  },
  matriz9_23: {
    geometries: ["matriz9_23_1", "matriz9_23_2"],
    name: "matriz9_23",
    image: "",
  },
  matriz9_24: {
    geometries: ["matriz9_24_1", "matriz9_24_2"],
    name: "matriz9_24",
    image: "",
  },
  matriz9_25: {
    geometries: ["matriz9_25_1", "matriz9_25_2"],
    name: "matriz9_25",
    image: "",
  },
  matriz9_26: {
    geometries: ["matriz9_26_1", "matriz9_26_2"],
    name: "matriz9_26",
    image: "",
  },
  matriz9_27: {
    geometries: ["matriz9_27_1", "matriz9_27_2"],
    name: "matriz9_27",
    image: "",
  },
  matriz9_28: {
    geometries: ["matriz9_28_1", "matriz9_28_2"],
    name: "matriz9_28",
    image: "",
  },
  matriz9_29: {
    geometries: ["matriz9_29_1", "matriz9_29_2"],
    name: "matriz9_29",
    image: "",
  },
  matriz9_30: {
    geometries: ["matriz9_30_1", "matriz9_30_2"],
    name: "matriz9_30",
    image: "",
  },
  matriz9_31: {
    geometries: ["matriz9_31_1", "matriz9_31_2"],
    name: "matriz9_31",
    image: "",
  },
  matriz9_32: {
    geometries: ["matriz9_32_1", "matriz9_32_2"],
    name: "matriz9_32",
    image: "",
  },
  matriz9_33: {
    geometries: ["matriz9_33_1", "matriz9_33_2"],
    name: "matriz9_33",
    image: "",
  },
  matriz9_34: {
    geometries: ["matriz9_34_1", "matriz9_34_2"],
    name: "matriz9_34",
    image: "",
  },
  matriz9_35: {
    geometries: ["matriz9_35_1", "matriz9_35_2"],
    name: "matriz9_35",
    image: "",
  },
  matriz9_36: {
    geometries: ["matriz9_36_1", "matriz9_36_2"],
    name: "matriz9_36",
    image: "",
  },
  matriz9_37: {
    geometries: ["matriz9_37_1", "matriz9_37_2"],
    name: "matriz9_37",
    image: "",
  },
  matriz9_38: {
    geometries: ["matriz9_38_1", "matriz9_38_2"],
    name: "matriz9_38",
    image: "",
  },
  matriz9_39: {
    geometries: ["matriz9_39_1", "matriz9_39_2"],
    name: "matriz9_39",
    image: "",
  },
  matriz9_40: {
    geometries: ["matriz9_40_1", "matriz9_40_2"],
    name: "matriz9_40",
    image: "",
  },
  matriz10_1: {
    geometries: ["matriz10_1_1", "matriz10_1_2"],
    name: "matriz10_1",
    image: "",
  },
  matriz10_2: {
    geometries: ["matriz10_2_1", "matriz10_2_2"],
    name: "matriz10_2",
    image: "",
  },
  matriz11_1: {
    geometries: ["matriz11_1_1", "matriz11_1_2"],
    name: "matriz11_1",
    image: "",
  },
  matriz11_2: {
    geometries: ["matriz11_2_1", "matriz11_2_2"],
    name: "matriz11_2",
    image: "",
  },
  matriz11_3: {
    geometries: ["matriz11_3_1", "matriz11_3_2"],
    name: "matriz11_3",
    image: "",
  },
  matriz11_4: {
    geometries: ["matriz11_4_1", "matriz11_4_2"],
    name: "matriz11_4",
    image: "",
  },
  matriz11_5: {
    geometries: ["matriz11_5_1", "matriz11_5_2"],
    name: "matriz11_5",
    image: "",
  },
  matriz11_6: {
    geometries: ["matriz11_6_1", "matriz11_6_2"],
    name: "matriz11_6",
    image: "",
  },
  matriz11_7: {
    geometries: ["matriz11_7_1", "matriz11_7_2"],
    name: "matriz11_7",
    image: "",
  },
  matriz11_8: {
    geometries: ["matriz11_8_1", "matriz11_8_2"],
    name: "matriz11_8",
    image: "",
  },
  matriz11_9: {
    geometries: ["matriz11_9_1", "matriz11_9_2"],
    name: "matriz11_9",
    image: "",
  },
  matriz11_10: {
    geometries: ["matriz11_10_1", "matriz11_10_2"],
    name: "matriz11_10",
    image: "",
  },
  matriz11_11: {
    geometries: ["matriz11_11_1", "matriz11_11_2"],
    name: "matriz11_11",
    image: "",
  },
  matriz11_12: {
    geometries: ["matriz11_12_1", "matriz11_12_2"],
    name: "matriz11_12",
    image: "",
  },
  matriz11_13: {
    geometries: ["matriz11_13_1", "matriz11_13_2"],
    name: "matriz11_13",
    image: "",
  },
  matriz11_14: {
    geometries: ["matriz11_14_1", "matriz11_14_2"],
    name: "matriz11_14",
    image: "",
  },
  matriz11_15: {
    geometries: ["matriz11_15_1", "matriz11_15_2"],
    name: "matriz11_15",
    image: "",
  },
  matriz11_16: {
    geometries: ["matriz11_16_1", "matriz11_16_2"],
    name: "matriz11_16",
    image: "",
  },
  matriz11_17: {
    geometries: ["matriz11_17_1", "matriz11_17_2"],
    name: "matriz11_17",
    image: "",
  },
  matriz11_18: {
    geometries: ["matriz11_18_1", "matriz11_18_2"],
    name: "matriz11_18",
    image: "",
  },
  matriz11_19: {
    geometries: ["matriz11_19_1", "matriz11_19_2"],
    name: "matriz11_19",
    image: "",
  },
  matriz11_20: {
    geometries: ["matriz11_20_1", "matriz11_20_2"],
    name: "matriz11_20",
    image: "",
  },
  matriz11_21: {
    geometries: ["matriz11_21_1", "matriz11_21_2"],
    name: "matriz11_21",
    image: "",
  },
  matriz11_22: {
    geometries: ["matriz11_22_1", "matriz11_22_2"],
    name: "matriz11_22",
    image: "",
  },
  matriz11_23: {
    geometries: ["matriz11_23_1", "matriz11_23_2"],
    name: "matriz11_23",
    image: "",
  },
  matriz11_24: {
    geometries: ["matriz11_24_1", "matriz11_24_2"],
    name: "matriz11_24",
    image: "",
  },
  matriz11_25: {
    geometries: ["matriz11_25_1", "matriz11_25_2"],
    name: "matriz11_25",
    image: "",
  },
  matriz11_26: {
    geometries: ["matriz11_26_1", "matriz11_26_2"],
    name: "matriz11_26",
    image: "",
  },
  matriz11_27: {
    geometries: ["matriz11_27_1", "matriz11_27_2"],
    name: "matriz11_27",
    image: "",
  },
  matriz11_28: {
    geometries: ["matriz11_28_1", "matriz11_28_2"],
    name: "matriz11_28",
    image: "",
  },
  matriz11_29: {
    geometries: ["matriz11_29_1", "matriz11_29_2"],
    name: "matriz11_29",
    image: "",
  },
  matriz11_30: {
    geometries: ["matriz11_30_1", "matriz11_30_2"],
    name: "matriz11_30",
    image: "",
  },
  matriz11_31: {
    geometries: ["matriz11_31_1", "matriz11_31_2"],
    name: "matriz11_31",
    image: "",
  },
  matriz11_32: {
    geometries: ["matriz11_32_1", "matriz11_32_2"],
    name: "matriz11_32",
    image: "",
  },
  matriz11_33: {
    geometries: ["matriz11_33_1", "matriz11_33_2"],
    name: "matriz11_33",
    image: "",
  },
  matriz11_34: {
    geometries: ["matriz11_34_1", "matriz11_34_2"],
    name: "matriz11_34",
    image: "",
  },
  matriz12_1: {
    geometries: ["matriz12_1_1", "matriz12_1_2"],
    name: "matriz12_1",
    image: "",
  },
  matriz12_2: {
    geometries: ["matriz12_2_1", "matriz12_2_2"],
    name: "matriz12_2",
    image: "",
  },
  matriz12_3: {
    geometries: ["matriz12_3_1", "matriz12_3_2"],
    name: "matriz12_3",
    image: "",
  },
  matriz12_4: {
    geometries: ["matriz12_4_1", "matriz12_4_2"],
    name: "matriz12_4",
    image: "",
  },
  matriz12_5: {
    geometries: ["matriz12_5_1", "matriz12_5_2"],
    name: "matriz12_5",
    image: "",
  },
  matriz12_6: {
    geometries: ["matriz12_6_1", "matriz12_6_2"],
    name: "matriz12_6",
    image: "",
  },
  matriz12_7: {
    geometries: ["matriz12_7_1", "matriz12_7_2"],
    name: "matriz12_7",
    image: "",
  },
  matriz12_8: {
    geometries: ["matriz12_8_1", "matriz12_8_2"],
    name: "matriz12_8",
    image: "",
  },
  matriz12_9: {
    geometries: ["matriz12_9_1", "matriz12_9_2"],
    name: "matriz12_9",
    image: "",
  },
  matriz12_10: {
    geometries: ["matriz12_10_1", "matriz12_10_2"],
    name: "matriz12_10",
    image: "",
  },
  matriz12_11: {
    geometries: ["matriz12_11_1", "matriz12_11_2"],
    name: "matriz12_11",
    image: "",
  },
  matriz12_12: {
    geometries: ["matriz12_12_1", "matriz12_12_2"],
    name: "matriz12_12",
    image: "",
  },
  matriz12_13: {
    geometries: ["matriz12_13_1", "matriz12_13_2"],
    name: "matriz12_13",
    image: "",
  },
  matriz13_1: {
    geometries: ["matriz13_1_1", "matriz13_1_2"],
    name: "matriz13_1",
    image: "",
  },
  matriz13_2: {
    geometries: ["matriz13_2_1", "matriz13_2_2"],
    name: "matriz13_2",
    image: "",
  },
  matriz13_3: {
    geometries: ["matriz13_3_1", "matriz13_3_2"],
    name: "matriz13_3",
    image: "",
  },
  matriz13_4: {
    geometries: ["matriz13_4_1", "matriz13_4_2"],
    name: "matriz13_4",
    image: "",
  },
  matriz14_1: {
    geometries: ["matriz14_1_1", "matriz14_1_2"],
    name: "matriz14_1",
    image: "",
  },
  matriz14_2: {
    geometries: ["matriz14_2_1", "matriz14_2_2"],
    name: "matriz14_2",
    image: "",
  },
  matriz15_1: {
    geometries: ["matriz15_1_1", "matriz15_1_2"],
    name: "matriz15_1",
    image: "",
  },
  matriz15_2: {
    geometries: ["matriz15_2_1", "matriz15_2_2"],
    name: "matriz15_2",
    image: "",
  },
  matriz15_3: {
    geometries: ["matriz15_3_1", "matriz15_3_2"],
    name: "matriz15_3",
    image: "",
  },
  matriz15_4: {
    geometries: ["matriz15_4_1", "matriz15_4_2"],
    name: "matriz15_4",
    image: "",
  },
  matriz15_5: {
    geometries: ["matriz15_5_1", "matriz15_5_2"],
    name: "matriz15_5",
    image: "",
  },
  matriz15_6: {
    geometries: ["matriz15_6_1", "matriz15_6_2"],
    name: "matriz15_6",
    image: "",
  },
};
// const categorizedMeshes = {
//   Categoria1: [
//     { mesh: nodes.matriz1_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz1_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz1_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz1_c_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria2: [
//     { mesh: nodes.matriz2_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz2_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz2_n_2.geometry, material: materials.Aluminio },
//   ],
//   // Agrega más categorías según sea necesario...
//   Categoria3: [
//     { mesh: nodes.matriz3_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz3_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz3_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria4: [
//     { mesh: nodes.matriz4_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz4_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz4_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz4_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria5: [
//     { mesh: nodes.matriz5_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz5_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz5_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria6: [
//     { mesh: nodes.matriz6_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz6_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz6_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz6_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria7: [
//     { mesh: nodes.matriz7_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_b_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_c_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_c_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_d_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_d_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_e_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_e_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_f_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_f_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_g_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_g_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_h_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_h_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_i_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_i_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_j_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_j_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_k_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_k_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_l_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_l_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_m_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_m_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_n_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_n_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_o_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_o_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_p_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_p_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_q_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_q_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_r_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_r_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_s_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_s_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz7_t_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz7_t_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria8: [
//     { mesh: nodes.matriz8_a_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz8_a_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz8_b_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz8_b_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria9: [
//     { mesh: nodes.matriz9_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_13_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_14_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_14_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_15_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_15_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_16_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_16_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_17_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_17_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_18_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_18_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_19_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_19_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_20_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_20_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_21_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_21_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_22_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_22_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_23_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_23_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_24_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_24_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_25_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_25_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_26_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_26_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_27_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_27_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_28_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_28_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_29_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_29_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_30_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_30_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_31_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_31_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_32_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_32_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_33_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_33_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_34_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_34_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_35_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_35_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_36_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_36_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_37_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_37_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_38_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_38_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_39_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_39_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz9_40_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz9_40_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria10: [
//     { mesh: nodes.matriz10_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz10_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz10_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz10_2_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria11: [
//     { mesh: nodes.matriz11_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_13_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_14_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_14_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_15_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_15_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_16_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_16_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_17_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_17_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_18_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_18_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_19_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_19_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_20_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_20_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_21_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_21_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_22_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_22_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_23_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_23_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_24_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_24_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_25_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_25_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_26_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_26_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_27_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_27_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_28_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_28_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_29_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_29_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_30_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_30_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_31_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_31_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_32_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_32_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_33_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_33_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz11_34_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz11_34_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria12: [
//     { mesh: nodes.matriz12_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_6_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_7_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_7_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_8_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_8_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_9_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_9_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_10_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_10_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_11_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_11_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_12_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_12_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz12_13_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz12_13_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria13: [
//     { mesh: nodes.matriz13_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz13_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz13_4_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria14: [
//     { mesh: nodes.matriz14_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz14_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz14_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz14_2_2.geometry, material: materials.Aluminio },
//   ],
//   Categoria15: [
//     { mesh: nodes.matriz15_1_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_1_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_2_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_2_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_3_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_3_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_4_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_4_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_5_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_5_2.geometry, material: materials.Aluminio },
//     { mesh: nodes.matriz15_6_1.geometry, material: materials.Base },
//     { mesh: nodes.matriz15_6_2.geometry, material: materials.Aluminio },
//   ],
// };

// const meshesToShow = categorizedMeshes[selectedCategory];
