/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 EscenaTXT.glb --transform -j -s 
Files: EscenaTXT.glb [6.73MB] > C:\Users\7475\Desktop\Trabajo\Dolc-Modificaciones\public\EscenaTXT-transformed.glb [793.65KB] (88%)
*/

import React, { useEffect, useState, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useConfigStore } from "./store";
import { TextureLoader, SRGBColorSpace } from "three";
import { TIPOS_MATERIAL, getImagenesParaMaterial } from "./texturas";
import { CatalogoPerfiles } from "./Materiales"; // Added import for CatalogoPerfiles
import * as THREE from "three"; // Added THREE import
import { getRandomMaterial, preloadPercentageTextures, selectMaterialByPercentage } from "./utils";
export function EscenaTXT(props) {
	const { nodes, materials } = useGLTF("/EscenaTXT.glb");
	const { invalidate } = useThree();
	const { onSectionClick, ...groupProps } = props;
	const genericPerfilMaterialRef = useRef(new THREE.MeshStandardMaterial({ name: "GenericPerfilMaterial" }));
	const {
		sistemaActivo,
		Section1,
		Section2,
		Section3,
		Section4,
		Section5,
		Section6,
		materialPorcelanico1,
		materialPorcelanico2,
		materialPorcelanico3,
		porcentajeMaterial1,
		porcentajeMaterial2,
		porcentajeMaterial3,
		materialPerfilSeleccionado, // Now correctly sourced from useConfigStore
	} = useConfigStore();

	const textureLoaderRef = useRef(new THREE.TextureLoader()); // Use a ref for the texture loader

	// Preloaded textures for all materials
	const [texturasPreCargadas, setTexturasPreCargadas] = useState({});

	// Store the material selection for each piece
	const [seleccionPorPieza, setSeleccionPorPieza] = useState({});

	// Preload textures for all three materials
	useEffect(() => {
		const cargarTexturas = async () => {
			try {
				const texturas = await preloadPercentageTextures(
					textureLoaderRef.current,
					{
						materialPorcelanico1,
						materialPorcelanico2,
						materialPorcelanico3,
					},
					getImagenesParaMaterial
				);
				setTexturasPreCargadas(texturas);
				console.log("Texturas pre-cargadas:", Object.keys(texturas));
			} catch (error) {
				console.error("Error al precargar texturas:", error);
			}
		};

		cargarTexturas();

		// Initialize or update material selection for each piece based on percentages
		const nuevaSeleccion = {};
		const materialsConfig = [
			{ id: materialPorcelanico1, percentage: porcentajeMaterial1 },
			{ id: materialPorcelanico2, percentage: porcentajeMaterial2 },
			{ id: materialPorcelanico3, percentage: porcentajeMaterial3 },
		];

		// For each material slot (Pieza01 to Pieza18), select a material based on percentages
		for (let i = 1; i <= 18; i++) {
			const materialKey = `Pieza${i.toString().padStart(2, "0")}`;
			nuevaSeleccion[materialKey] = selectMaterialByPercentage(materialsConfig);
		}

		setSeleccionPorPieza(nuevaSeleccion);
	}, [materialPorcelanico1, materialPorcelanico2, materialPorcelanico3, porcentajeMaterial1, porcentajeMaterial2, porcentajeMaterial3]);

	useEffect(() => {
		if (materials && Object.keys(texturasPreCargadas).length > 0 && Object.keys(seleccionPorPieza).length > 0) {
			console.log("Aplicando texturas basadas en selección por pieza");
			let changed = false;

			// Apply textures based on the pre-selected materials for each piece
			Object.entries(seleccionPorPieza).forEach(([materialKey, selectedMaterialId]) => {
				if (materials[materialKey] && materials[materialKey].isMeshStandardMaterial) {
					// Extract the index from the material key (Pieza01 -> 1)
					const index = parseInt(materialKey.replace("Pieza", ""), 10);

					// Get textures for the selected material
					const texturasDelMaterial = texturasPreCargadas[selectedMaterialId] || [];

					// Apply the corresponding texture to this material slot
					if (texturasDelMaterial.length > 0 && index <= texturasDelMaterial.length) {
						const textura = texturasDelMaterial[index - 1]; // Use 0-based index
						if (textura) {
							// Assign the texture to the material
							materials[materialKey].map = textura;
							// Reset material properties to ensure proper texture display
							materials[materialKey].color.set(0xffffff); // Reset color to white
							materials[materialKey].roughness = 1; // Adjust roughness for ceramic materials
							materials[materialKey].metalness = 0; // Ensure non-metallic
							materials[materialKey].needsUpdate = true; // Mark for update
							changed = true;
						}
					}
				}
			});

			// If changes were made, invalidate the scene to force re-rendering
			if (changed) {
				invalidate();
				console.log("Texturas aplicadas basadas en selección por pieza y escena invalidada");
			}
		}
	}, [materials, texturasPreCargadas, seleccionPorPieza, invalidate]);
	useEffect(() => {
		const targetMaterial = genericPerfilMaterialRef.current; // Use our generic material

		if (materialPerfilSeleccionado && CatalogoPerfiles[materialPerfilSeleccionado]) {
			const perfilMaterialConfig = CatalogoPerfiles[materialPerfilSeleccionado];
			console.log("Applying profile material:", perfilMaterialConfig);

			targetMaterial.roughness = perfilMaterialConfig.roughness;
			targetMaterial.metalness = perfilMaterialConfig.metalness;

			const oldMap = targetMaterial.map; // Store current map to potentially dispose later

			if (perfilMaterialConfig.mainTexture) {
				console.log(`Loading profile texture: ${perfilMaterialConfig.mainTexture}`);
				textureLoaderRef.current.load(
					perfilMaterialConfig.mainTexture,
					(loadedTexture) => {
						console.log("Profile texture loaded successfully:", loadedTexture);
						if (oldMap && oldMap !== loadedTexture) {
							oldMap.dispose();
						} // Optional: dispose old texture
						loadedTexture.flipY = false;
						loadedTexture.colorSpace = THREE.SRGBColorSpace;

						targetMaterial.map = loadedTexture;
						targetMaterial.color.set(0xffffff); // Reset color to white when texture is applied
						targetMaterial.needsUpdate = true;
						invalidate(); // Trigger a re-render
					},
					undefined, // onProgress
					(error) => {
						console.error(`Error loading profile texture: ${perfilMaterialConfig.mainTexture}`, error);
						if (oldMap) {
							oldMap.dispose();
						}
						targetMaterial.map = null;
						targetMaterial.color.set(0xcccccc); // Example fallback color
						targetMaterial.needsUpdate = true;
						invalidate(); // Trigger a re-render
					}
				);
			} else if (perfilMaterialConfig.color) {
				console.log("Applying profile color:", perfilMaterialConfig.color);
				if (oldMap) {
					oldMap.dispose();
				}
				targetMaterial.map = null; // Remove any existing texture
				targetMaterial.color.set(perfilMaterialConfig.color);
				// targetMaterial.colorSpace = THREE.SRGBColorSpace; // For colors, usually NoColorSpace or be mindful of conversions
				targetMaterial.needsUpdate = true;
				invalidate(); // Trigger a re-render
			} else {
				console.log("Applying fallback profile material (no texture, default color)");
				if (oldMap) {
					oldMap.dispose();
				}
				targetMaterial.map = null;
				targetMaterial.color.set(0xffffff); // Default to white
				// targetMaterial.colorSpace = THREE.SRGBColorSpace;
				targetMaterial.needsUpdate = true;
				invalidate(); // Trigger a re-render
			}
		} else {
			console.log("No profile material selected or config not found, resetting to default.");
			const oldMap = targetMaterial.map;
			if (oldMap) {
				oldMap.dispose();
			}
			targetMaterial.map = null;
			targetMaterial.color.set(0xffffff); // Default color
			targetMaterial.roughness = 0.5; // Default roughness
			targetMaterial.metalness = 0.0; // Default metalness
			// targetMaterial.colorSpace = THREE.SRGBColorSpace;
			targetMaterial.needsUpdate = true;
			invalidate(); // Trigger a re-render
		}
	}, [materialPerfilSeleccionado, invalidate]); // Dependencies
	const getMaterialForMesh = (originalMaterialKey) => {
		// Return the base material - textures are now applied per piece in the useEffect
		return materials[originalMaterialKey] || null;
	};

	return (
		<group {...groupProps} dispose={null}>
			{sistemaActivo === "TXT 13" && (
				<>
					<group name="Seccion1" position={[0, 0, Section1]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_001.geometry} material={getMaterialForMesh("Pieza01")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_002.geometry} material={getMaterialForMesh("Pieza02")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_003.geometry} material={getMaterialForMesh("Pieza03")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_004.geometry} material={getMaterialForMesh("Pieza04")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_005.geometry} material={getMaterialForMesh("Pieza05")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_006.geometry} material={getMaterialForMesh("Pieza06")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_007.geometry} material={getMaterialForMesh("Pieza07")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_008.geometry} material={getMaterialForMesh("Pieza08")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_009.geometry} material={getMaterialForMesh("Pieza09")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_010.geometry} material={getMaterialForMesh("Pieza10")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_011.geometry} material={getMaterialForMesh("Pieza11")} />
					</group>
					<group name="Seccion2" position={[0, 0, Section2]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_012.geometry} material={getMaterialForMesh("Pieza03")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_013.geometry} material={getMaterialForMesh("Pieza04")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_014.geometry} material={getMaterialForMesh("Pieza12")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_015.geometry} material={getMaterialForMesh("Pieza13")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_016.geometry} material={getMaterialForMesh("Pieza14")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_017.geometry} material={getMaterialForMesh("Pieza15")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_018.geometry} material={getMaterialForMesh("Pieza16")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_019.geometry} material={getMaterialForMesh("Pieza17")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_020.geometry} material={getMaterialForMesh("Pieza18")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_021.geometry} material={getMaterialForMesh("Pieza01")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_022.geometry} material={getMaterialForMesh("Pieza02")} />
					</group>
					<group name="Seccion3" position={[0, 0, Section3]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_023.geometry} material={getMaterialForMesh("Pieza14")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_024.geometry} material={getMaterialForMesh("Pieza15")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_025.geometry} material={getMaterialForMesh("Pieza05")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_026.geometry} material={getMaterialForMesh("Pieza06")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_027.geometry} material={getMaterialForMesh("Pieza07")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_028.geometry} material={getMaterialForMesh("Pieza08")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_029.geometry} material={getMaterialForMesh("Pieza09")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_030.geometry} material={getMaterialForMesh("Pieza10")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_031.geometry} material={getMaterialForMesh("Pieza11")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_032.geometry} material={getMaterialForMesh("Pieza12")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_033.geometry} material={getMaterialForMesh("Pieza13")} />
					</group>
					<group name="Seccion4" position={[0, 0, Section4]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_034.geometry} material={getMaterialForMesh("Pieza07")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_035.geometry} material={getMaterialForMesh("Pieza08")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_036.geometry} material={getMaterialForMesh("Pieza16")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_037.geometry} material={getMaterialForMesh("Pieza17")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_038.geometry} material={getMaterialForMesh("Pieza18")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_039.geometry} material={getMaterialForMesh("Pieza01")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_040.geometry} material={getMaterialForMesh("Pieza02")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_041.geometry} material={getMaterialForMesh("Pieza03")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_042.geometry} material={getMaterialForMesh("Pieza04")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_043.geometry} material={getMaterialForMesh("Pieza05")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_044.geometry} material={getMaterialForMesh("Pieza06")} />
					</group>
					<group name="Seccion5" position={[0, 0, Section5]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_045.geometry} material={getMaterialForMesh("Pieza18")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_046.geometry} material={getMaterialForMesh("Pieza01")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_047.geometry} material={getMaterialForMesh("Pieza09")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_048.geometry} material={getMaterialForMesh("Pieza10")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_049.geometry} material={getMaterialForMesh("Pieza11")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_050.geometry} material={getMaterialForMesh("Pieza12")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_051.geometry} material={getMaterialForMesh("Pieza13")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_052.geometry} material={getMaterialForMesh("Pieza14")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_053.geometry} material={getMaterialForMesh("Pieza15")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_054.geometry} material={getMaterialForMesh("Pieza16")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_055.geometry} material={getMaterialForMesh("Pieza17")} />
					</group>
					<group name="Seccion6" position={[0, 0, Section6]}>
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_056.geometry} material={getMaterialForMesh("Pieza11")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_057.geometry} material={getMaterialForMesh("Pieza12")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_058.geometry} material={getMaterialForMesh("Pieza02")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_059.geometry} material={getMaterialForMesh("Pieza03")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_060.geometry} material={getMaterialForMesh("Pieza04")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_061.geometry} material={getMaterialForMesh("Pieza05")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_062.geometry} material={getMaterialForMesh("Pieza06")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_063.geometry} material={getMaterialForMesh("Pieza07")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_064.geometry} material={getMaterialForMesh("Pieza08")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_065.geometry} material={getMaterialForMesh("Pieza09")} />
						<mesh castShadow receiveShadow geometry={nodes.PIEZA_TXT_13_066.geometry} material={getMaterialForMesh("Pieza10")} />
					</group>
					<group name="PerfilesTXT13" position={[0, 0, 0.09]}>
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_001.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_002.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_003.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_004.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_005.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_006.geometry} material={genericPerfilMaterialRef.current} />
						<mesh castShadow receiveShadow geometry={nodes.PERFIL_FIJO_007.geometry} material={genericPerfilMaterialRef.current} />
					</group>
				</>
			)}
			<>
				<group name="Seccion1 TXT11" position={[0, 0, Section1]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_001.geometry} material={getMaterialForMesh("Pieza01")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_002.geometry} material={getMaterialForMesh("Pieza02")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_003.geometry} material={getMaterialForMesh("Pieza03")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_004.geometry} material={getMaterialForMesh("Pieza04")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_005.geometry} material={getMaterialForMesh("Pieza05")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_006.geometry} material={getMaterialForMesh("Pieza06")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_007.geometry} material={getMaterialForMesh("Pieza07")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_008.geometry} material={getMaterialForMesh("Pieza08")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_009.geometry} material={getMaterialForMesh("Pieza09")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_010.geometry} material={getMaterialForMesh("Pieza10")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_011.geometry} material={getMaterialForMesh("Pieza11")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_001.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion2 TXT11" position={[0, 0, Section2]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_012.geometry} material={getMaterialForMesh("Pieza18")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_013.geometry} material={getMaterialForMesh("Pieza01")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_014.geometry} material={getMaterialForMesh("Pieza17")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_015.geometry} material={getMaterialForMesh("Pieza02")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_016.geometry} material={getMaterialForMesh("Pieza03")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_017.geometry} material={getMaterialForMesh("Pieza12")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_018.geometry} material={getMaterialForMesh("Pieza13")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_019.geometry} material={getMaterialForMesh("Pieza14")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_020.geometry} material={getMaterialForMesh("Pieza15")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_021.geometry} material={getMaterialForMesh("Pieza16")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_022.geometry} material={getMaterialForMesh("Pieza04")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_002.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion3 TXT11" position={[0, 0, Section3]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_023.geometry} material={getMaterialForMesh("Pieza11")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_024.geometry} material={getMaterialForMesh("Pieza12")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_025.geometry} material={getMaterialForMesh("Pieza10")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_026.geometry} material={getMaterialForMesh("Pieza13")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_027.geometry} material={getMaterialForMesh("Pieza14")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_028.geometry} material={getMaterialForMesh("Pieza05")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_029.geometry} material={getMaterialForMesh("Pieza06")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_030.geometry} material={getMaterialForMesh("Pieza07")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_031.geometry} material={getMaterialForMesh("Pieza08")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_032.geometry} material={getMaterialForMesh("Pieza09")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_033.geometry} material={getMaterialForMesh("Pieza15")} />

					<mesh castShadow receiveShadow geometry={nodes.PERFIL_003.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion4 TXT11" position={[0, 0, Section4]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_034.geometry} material={getMaterialForMesh("Pieza04")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_035.geometry} material={getMaterialForMesh("Pieza05")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_036.geometry} material={getMaterialForMesh("Pieza03")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_037.geometry} material={getMaterialForMesh("Pieza06")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_038.geometry} material={getMaterialForMesh("Pieza07")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_039.geometry} material={getMaterialForMesh("Pieza16")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_040.geometry} material={getMaterialForMesh("Pieza17")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_041.geometry} material={getMaterialForMesh("Pieza18")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_042.geometry} material={getMaterialForMesh("Pieza01")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_043.geometry} material={getMaterialForMesh("Pieza02")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_044.geometry} material={getMaterialForMesh("Pieza08")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_004.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion5 TXT11" position={[0, 0, Section5]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_045.geometry} material={getMaterialForMesh("Pieza15")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_046.geometry} material={getMaterialForMesh("Pieza16")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_047.geometry} material={getMaterialForMesh("Pieza14")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_048.geometry} material={getMaterialForMesh("Pieza17")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_049.geometry} material={getMaterialForMesh("Pieza18")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_050.geometry} material={getMaterialForMesh("Pieza09")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_051.geometry} material={getMaterialForMesh("Pieza10")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_052.geometry} material={getMaterialForMesh("Pieza11")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_053.geometry} material={getMaterialForMesh("Pieza12")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_054.geometry} material={getMaterialForMesh("Pieza13")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_055.geometry} material={getMaterialForMesh("Pieza01")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_005.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion6 TXT11" position={[0, 0, Section6]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_056.geometry} material={getMaterialForMesh("Pieza08")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_057.geometry} material={getMaterialForMesh("Pieza09")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_058.geometry} material={getMaterialForMesh("Pieza07")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_059.geometry} material={getMaterialForMesh("Pieza10")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_060.geometry} material={getMaterialForMesh("Pieza11")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_061.geometry} material={getMaterialForMesh("Pieza02")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_062.geometry} material={getMaterialForMesh("Pieza03")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_063.geometry} material={getMaterialForMesh("Pieza04")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_064.geometry} material={getMaterialForMesh("Pieza05")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_065.geometry} material={getMaterialForMesh("Pieza06")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_066.geometry} material={getMaterialForMesh("Pieza12")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_006.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<group name="Seccion7 TXT11" position={[0, 0, 0]}>
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_067.geometry} material={getMaterialForMesh("Pieza01")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_068.geometry} material={getMaterialForMesh("Pieza02")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_069.geometry} material={getMaterialForMesh("Pieza18")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_070.geometry} material={getMaterialForMesh("Pieza03")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_071.geometry} material={getMaterialForMesh("Pieza04")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_072.geometry} material={getMaterialForMesh("Pieza13")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_073.geometry} material={getMaterialForMesh("Pieza14")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_074.geometry} material={getMaterialForMesh("Pieza15")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_075.geometry} material={getMaterialForMesh("Pieza16")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_076.geometry} material={getMaterialForMesh("Pieza17")} />
					<mesh castShadow receiveShadow geometry={nodes.PIEZA_077.geometry} material={getMaterialForMesh("Pieza05")} />
					<mesh castShadow receiveShadow geometry={nodes.PERFIL_007.geometry} material={genericPerfilMaterialRef.current} />
				</group>
				<mesh castShadow receiveShadow geometry={nodes.PERFIL_000.geometry} material={genericPerfilMaterialRef.current} />
			</>

			<mesh castShadow receiveShadow geometry={nodes.BARANDILLAS.geometry} material={materials.Aluminio} />
			<mesh castShadow receiveShadow geometry={nodes.CARCASA_EDIFICIO_1.geometry} material={materials.Fondo} />
			<mesh castShadow receiveShadow geometry={nodes.CARCASA_EDIFICIO_2.geometry} material={materials.Material}>
				<meshStandardMaterial color={"#9e9e9e"} roughness={1} metalness={0} />
			</mesh>
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_1.geometry} material={getMaterialForMesh("Pieza01")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_2.geometry} material={getMaterialForMesh("Pieza01")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_3.geometry} material={getMaterialForMesh("Pieza02")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_4.geometry} material={getMaterialForMesh("Pieza03")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_5.geometry} material={getMaterialForMesh("Pieza04")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_6.geometry} material={getMaterialForMesh("Pieza05")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_7.geometry} material={getMaterialForMesh("Pieza06")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_8.geometry} material={getMaterialForMesh("Pieza07")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_9.geometry} material={getMaterialForMesh("Pieza08")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_10.geometry} material={getMaterialForMesh("Pieza09")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_11.geometry} material={getMaterialForMesh("Pieza10")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_12.geometry} material={getMaterialForMesh("Pieza11")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_13.geometry} material={getMaterialForMesh("Pieza12")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_14.geometry} material={getMaterialForMesh("Pieza13")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_15.geometry} material={getMaterialForMesh("Pieza14")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_16.geometry} material={getMaterialForMesh("Pieza15")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_17.geometry} material={getMaterialForMesh("Pieza16")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_18.geometry} material={getMaterialForMesh("Pieza17")} />
			<mesh castShadow receiveShadow geometry={nodes.CERAMICA_EDIFICIO_19.geometry} material={getMaterialForMesh("Pieza18")} />
			<mesh
				// castShadow
				geometry={nodes.CRISTALES_BARANDILLAS.geometry}
				material={materials.Cristal}
			/>

			<mesh castShadow receiveShadow geometry={nodes.LUCECITAS.geometry}>
				<meshStandardMaterial color={"#ffffff"} roughness={0.5} metalness={0.1} />
			</mesh>
			<mesh castShadow receiveShadow geometry={nodes.PARED_FACHADA_TXT.geometry} material={materials.Fondo} />
			<mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
			<mesh castShadow receiveShadow geometry={nodes.Rectangle2926.geometry} material={materials.Aluminio} />
			<mesh castShadow receiveShadow geometry={nodes.VENTANAS_1.geometry} material={materials.Cristal} />
			<mesh castShadow receiveShadow geometry={nodes.VENTANAS_2.geometry} material={materials.Marco_Ventana} />
		</group>
	);
}

useGLTF.preload("/EscenaTXT-transformed.glb");
