// store.jsx
import { create } from "zustand";
import { Mallas } from "./Mallas";
import { Materiales } from "./Materiales";

const useStore = create((set) => ({
  // Estados generales
  materialIndex1: 0,
  materialIndex2: 0,
  materialIndex3: 0,
  materialIndex4: 0,
  materialIndex5: 0,
  materialIndex6: 0,
  showIntro: true,
  selected: false,
  color: "#ffffff",
  color1: "#ffffff",
  color2: "#ffffff",
  color3: "#ffffff",
  color4: "#ffffff",
  color5: "#ffffff",
  color6: "#ffffff",
  colorPickerActive: false,
  selectedMatrix1: Mallas[2].matrices[13],
  selectedMatrix2: Mallas[2].matrices[13],
  selectedMatrix3: Mallas[2].matrices[13],
  selectedMatrix4: Mallas[2].matrices[13],
  selectedMatrix5: Mallas[2].matrices[13],
  selectedMatrix6: Mallas[2].matrices[13],
  isMenuOpen: false,
  selectedModel1: false,
  selectedModel2: false,
  selectedModel3: false,
  selectedModel4: false,
  selectedModel5: false,
  selectedModel6: false,
  materialSource1: null,
  materialSource2: null,
  materialSource3: null,
  materialSource4: null,
  materialSource5: null,
  materialSource6: null,
  materialMalla1: Materiales[0].map,
  materialMalla2: Materiales[0].map,
  materialMalla3: Materiales[0].map,
  materialMalla4: Materiales[0].map,
  materialMalla5: Materiales[0].map,
  materialMalla6: Materiales[0].map,
  numModels: 1,
  selectedGeo1Model1: "matriz3_m_1",
  selectedGeo2Model1: "matriz3_m_2",
  selectedGeo1Model2: "matriz3_m_1",
  selectedGeo2Model2: "matriz3_m_2",
  selectedGeo1Model3: "matriz3_m_1",
  selectedGeo2Model3: "matriz3_m_2",
  selectedGeo1Model4: "matriz3_m_1",
  selectedGeo2Model4: "matriz3_m_2",
  selectedGeo1Model5: "matriz3_m_1",
  selectedGeo2Model5: "matriz3_m_2",
  selectedGeo1Model6: "matriz3_m_1",
  selectedGeo2Model6: "matriz3_m_2",
  leivaSelected: false,

  // Acciones para actualizar los estados generales
  setMaterialIndex1: (index) => set({ materialIndex1: index }),
  setMaterialIndex2: (index) => set({ materialIndex2: index }),
  setMaterialIndex3: (index) => set({ materialIndex3: index }),
  setMaterialIndex4: (index) => set({ materialIndex4: index }),
  setMaterialIndex5: (index) => set({ materialIndex5: index }),
  setMaterialIndex6: (index) => set({ materialIndex6: index }),
  setShowIntro: (show) => set({ showIntro: show }),
  setSelected: (selected) => set({ selected: selected }),
  setColor1: (color) => set({ color1: color }),
  setColor2: (color) => set({ color2: color }),
  setColor3: (color) => set({ color3: color }),
  setColor4: (color) => set({ color4: color }),
  setColor5: (color) => set({ color5: color }),
  setColor6: (color) => set({ color6: color }),
  setColorPickerActive: (active) => set({ colorPickerActive: active }),
  setSelectedMatrix1: (matrix) => set({ selectedMatrix1: matrix }),
  setSelectedMatrix2: (matrix) => set({ selectedMatrix2: matrix }),
  setSelectedMatrix3: (matrix) => set({ selectedMatrix3: matrix }),
  setSelectedMatrix4: (matrix) => set({ selectedMatrix4: matrix }),
  setSelectedMatrix5: (matrix) => set({ selectedMatrix5: matrix }),
  setSelectedMatrix6: (matrix) => set({ selectedMatrix6: matrix }),
  setIsMenuOpen: (open) => set({ isMenuOpen: open }),
  setSelectedModel1: (model) => set({ selectedModel1: model }),
  setSelectedModel2: (model) => set({ selectedModel2: model }),
  setSelectedModel3: (model) => set({ selectedModel3: model }),
  setSelectedModel4: (model) => set({ selectedModel4: model }),
  setSelectedModel5: (model) => set({ selectedModel5: model }),
  setSelectedModel6: (model) => set({ selectedModel6: model }),
  setMaterialSource1: (source) => set({ materialSource1: source }),
  setMaterialSource2: (source) => set({ materialSource2: source }),
  setMaterialSource3: (source) => set({ materialSource3: source }),
  setMaterialSource4: (source) => set({ materialSource4: source }),
  setMaterialSource5: (source) => set({ materialSource5: source }),
  setMaterialSource6: (source) => set({ materialSource6: source }),
  setMaterialMalla1: (texture) => set({ materialMalla1: texture }),
  setMaterialMalla2: (texture) => set({ materialMalla2: texture }),
  setMaterialMalla3: (texture) => set({ materialMalla3: texture }),
  setMaterialMalla4: (texture) => set({ materialMalla4: texture }),
  setMaterialMalla5: (texture) => set({ materialMalla5: texture }),
  setMaterialMalla6: (texture) => set({ materialMalla6: texture }),
  setNumModels: (num) => set({ numModels: num }),
  setSelectedGeo1Model1: (geo) => set({ selectedGeo1Model1: geo }),
  setSelectedGeo2Model1: (geo) => set({ selectedGeo2Model1: geo }),
  setSelectedGeo1Model2: (geo) => set({ selectedGeo1Model2: geo }),
  setSelectedGeo2Model2: (geo) => set({ selectedGeo2Model2: geo }),
  setSelectedGeo1Model3: (geo) => set({ selectedGeo1Model3: geo }),
  setSelectedGeo2Model3: (geo) => set({ selectedGeo2Model3: geo }),
  setSelectedGeo1Model4: (geo) => set({ selectedGeo1Model4: geo }),
  setSelectedGeo2Model4: (geo) => set({ selectedGeo2Model4: geo }),
  setSelectedGeo1Model5: (geo) => set({ selectedGeo1Model5: geo }),
  setSelectedGeo2Model5: (geo) => set({ selectedGeo2Model5: geo }),
  setSelectedGeo1Model6: (geo) => set({ selectedGeo1Model6: geo }),
  setSelectedGeo2Model6: (geo) => set({ selectedGeo2Model6: geo }),
  setLeivaSelected: (selected) => set({ leivaSelected: selected }),
}));

export default useStore;
